### ISSUE TITLE
[SUGGESTION] Auto account parsing

### ISSUE THREAD

**Issue by Mike129812** [BeepFelix/csgo-commend-bot#1]
Maybe a feature to auto add user:pass steam accs to a file then it auto adds those to the accounts config?

**Comment by BeepFelix** [comment]
Alright thanks Github for not notifying me about this issue.

Multiple people have already asked me on Discord about it so I added it [here](https://github.com/BeepFelix/csgo-commend-bot/blob/master/parseAccountList.js).
See the [Account Parsing](https://github.com/BeepFelix/csgo-commend-bot#account-parsing) part of the README for a little help.
