### ISSUE TITLE
Using vac banned accounts for commendation.

### ISSUE THREAD

**Issue by namanchikara** [BeepFelix/csgo-commend-bot#100]
On using vac banned accounts for commendation instead of showing error such as : ```Vacced account couldn't be used for commending, removing account from database``` it results in : ```[zecjy_Dnv1tn] Failed to commend (10/20) { name: 'Error',
  message: 'Failed to send message: Timeout',
  stack:
   'Error: Failed to send message: Timeout\n    at Timeout.setTimeout [as _onTimeout] (D:\\csgo-commend-bot\\helpers\\GameCoordinator.js:161:12)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers
.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)' }```

**Comment by namanchikara** [comment]
What I'm suggesting is to notify user that you can't use vac banned accounts AND ALSO remove that accound from db for further commendations

**Comment by BeepFelix** [comment]
This has been added in version [2.2.4](https://github.com/BeepFelix/csgo-commend-bot/blob/master/CHANGELOG.md#224)

If issues occur report back here.
