### ISSUE TITLE
Failed To login problem help pls

### ISSUE THREAD

**Issue by chandantrader** [BeepFelix/csgo-commend-bot#102]
When I am trying to send commends it is showing me failed to send commends timeout. 

help me pls

**Comment by BeepFelix** [comment]
What even is your error?

**Comment by chandantrader** [comment]
https://cdn.discordapp.com/attachments/624896672241156107/625262773638791211/unknown.png

**Comment by BeepFelix** [comment]
What is your config? If you are using `SERVER` method what server are you using?

**Comment by chandantrader** [comment]
community server

**Comment by chandantrader** [comment]
in that server id i add the server ip

**Comment by BeepFelix** [comment]
Ignored my first question.

> What is your config?

Send your full config, remove API Key and account details before posting.

**Comment by chandantrader** [comment]
This is my config.js
https://ibb.co/KV7hytt

**Comment by Alexey25322** [comment]
> 
> 
> This is my config.js
> https://ibb.co/KV7hytt

You need an API key

**Comment by BeepFelix** [comment]
> > This is my config.js
> > https://ibb.co/KV7hytt
> 
> You need an API key

I said to removed it.

>Send your full config, **remove API Key and account details before posting**.

**Comment by Alexey25322** [comment]
Didn't see that

**Comment by chandantrader** [comment]
he said thats why i removed pls help now what shall i do?

**Comment by chandantrader** [comment]
some accs work some shows the error which i showed u above

**Comment by Alexey25322** [comment]
Are you sure the login details are correct?

**Comment by BeepFelix** [comment]
Good question, I have no idea what this could cause. It looks like your connection isn't strong enough to support logging into 20 accounts at once so Steam cannot send a response (?) *or something like that.*

**Comment by chandantrader** [comment]
the acc details are perfect as i tried to log in and it worked. and i tried on 3-4 connections, on my vps,laptop,pc,etc
still same error

**Comment by Alexey25322** [comment]
Did you start csgo atleast once on these accounts?

**Comment by chandantrader** [comment]
yes !

**Comment by chandantrader** [comment]
shall i change 20 to 15
chunk

**Comment by Alexey25322** [comment]
If you get this on the same accounts, i don't think changing the nummber of chunks will help, some kind of account issue

**Comment by BeepFelix** [comment]
I have no idea what the cause of this could be. What you can try though is on [line 27 of `account.js`](https://github.com/BeepFelix/csgo-commend-bot/blob/master/helpers/account.js#L27) change `timeout = 60000` to `timeout = 180000`, it will then wait 3 minutes before rejecting instead of 1 minute.

**Comment by chandantrader** [comment]
okay
let me try and i will let u know tomorrow.

**Comment by chandantrader** [comment]
may i know where is accounts.js

**Comment by Alexey25322** [comment]
http://juckt.xyz/1387662.png

**Comment by BeepFelix** [comment]
> may i know where is accounts.js

[The link shows where it is](https://i.imgur.com/TjrEdQL.png)

**Comment by chandantrader** [comment]
Thanks @BeepFelix it worked :D
