### ISSUE TITLE
Database Management Problem

### ISSUE THREAD

**Issue by MayankFawkes** [BeepFelix/csgo-commend-bot#107]
**Detailed bug description**
Not All account adding to the database.
From database manager, I added 30 accounts and when I export accounts it only returns 26 why 4 accounts are not acceptable.

note:
accounts are new and no vac banned

**Error**
```
No Error Showed
```

**Version**
- NodeJS: `v10.16.3` (You can find this using `node -v`)
- Script version: `2.2.4` (You can find this in **your** `package.json` file under `version`)

**Comment by BeepFelix** [comment]
I cannot reproduce this.

I tested it with 500 randomly generated usernames & passwords and it worked just fine.

What options are you selecting in the menu?

**Comment by MayankFawkes** [comment]
I am using a text file format 
username: password
I load 29 accounts and after when I export accounts from the database it returns 26
and can you please tell me from where I can generate accounts like 500 and so.

Thanks

**Comment by BeepFelix** [comment]
> I am using a text file format

I did the same and it worked just fine.

> I load 29 accounts and after when I export accounts from the database it returns 26

You might have duplicates in your list.

> can you please tell me from where I can generate accounts like 500 and so

[accgen.cathook.club](httos://accgen.cathook.club/) with a 2Captcha key and very *very* good proxies.

In my test I used pseudo accounts, they don't really exist.

**Comment by MayankFawkes** [comment]
Thanks
