### ISSUE TITLE
Failed to send message

### ISSUE THREAD

**Issue by catalinkn** [BeepFelix/csgo-commend-bot#108]
**Detailed bug description**

**Error**
```
A full error log or screenshot.
```

**Config**
```
Your "config.json" - Censor your API Key and account details
```

**Version**
- NodeJS: `vXX.XX.X` (You can find this using `node -v`)
- Script version: `X.X.X` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.
![bug_report](https://user-images.githubusercontent.com/56046450/65992644-4678e200-e498-11e9-80fc-c0d31d49d7cd.png)

**Comment by BeepFelix** [comment]
You didn't even fill out the template. It exists for a reason.

What is your config?
What method are you using?
What server type are you using? (Valve, or Community)

**Comment by catalinkn** [comment]
![confiogr](https://user-images.githubusercontent.com/56046450/66021808-866db280-e4f4-11e9-8626-83ecd505a66e.png)

**Comment by BeepFelix** [comment]
Doesn't look wrong, but looks a little outdated.

Anyways, there are many possible reasons for it to happen such as:
- Target left the server
- Server is now full
- Server does not have enough slots (Unconfirmed)
- Server is a Valve Matchmaking server
- Target hit the commend limit for (10 per 5 minutes)
- Server hit the total commend limit (150 - Unconfirmed)
- Steam is offline
- CSGO is offline
- I don't know maybe more?

Typically if it happens for an entire chunk just switching server resolves the issue.

That's all I know and all the info I can give.
