### ISSUE TITLE
I get this issue.

### ISSUE THREAD

**Issue by iusamaahmad** [BeepFelix/csgo-commend-bot#110]
Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 806 operational accounts
 Parsing target account...
{ type: 'FORBIDDEN', key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' } Promise {
  <rejected> { type: 'FORBIDDEN', key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' }

**Comment by BeepFelix** [comment]
You didn't do step 4 of the install instructions in the README.

You have to actually fill in an API key.
