### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by krzychuy** [BeepFelix/csgo-commend-bot#112]
Ive got two big problems, i added accoutns to database and when im trying to run commend bot its saying password is wrong but it isn't how to fix that?
And second big problem 
 Opening database...
 There are a total of 7 operational accounts
 Parsing target account...
{ type: 'FORBIDDEN', key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' } Promise {
  <rejected> { type: 'FORBIDDEN', key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' }
this, whats that. Please help me

**Comment by BeepFelix** [comment]
Same as #110
