### ISSUE TITLE
ERROR: Failed to send

### ISSUE THREAD

**Issue by krzychuy** [BeepFelix/csgo-commend-bot#114]
[PaleSatisfyingSandpiper02] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\krzys\\Desktop\\oglne\\PROGRAMY DO STEAMA\\COMMENDBOT\\helpers\\GameCoordinator.js:161:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'

What i need to do now?

**Comment by BeepFelix** [comment]
Many possibilities, read the last comment of #108
