### ISSUE TITLE
get the last time bot commend

### ISSUE THREAD

**Issue by parsaew** [BeepFelix/csgo-commend-bot#117]
**Detailed bug description**
When you commend someone ( for ex 100 commend )
after 24hour or even more, when you want to commend someone else the bot is not fully ready ( 30 account ready for commend ) 
how to fix this timing issue?

**Error**
```
![Untitled](https://user-images.githubusercontent.com/56785732/67156962-3be09880-f332-11e9-9724-4948bc236ed0.png)
```

**Config**
```
{
	"commend": {
		"friendly": 100,
		"teaching": 100,
		"leader": 100
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/76561198988790622/",
	"serverID": "5.63.11.198:27022",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "7xx"
}

```

**Version**
- NodeJS: `v12.10.0` (You can find this using `node -v`)
- Script version: `2.2.4` (You can find this in **your** `package.json` file under `version`)

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepFelix** [comment]
The cooldown is actually 8 hours, 3 times a day is equals to once every 8 hours.

---

Either they are indeed still on cooldown or have already commended your target.

If you doubt that's the actual issue download [SQLite Browser](https://sqlitebrowser.org/) and open up the `accounts.sqlite` file with it and check if the timestamps and everything is correct.

[Convert the `lastCommended` timestamps to a proper date/time](https://currentmillis.com/) and check if they are all over 8 hours ago.

**Comment by parsaew** [comment]
yeah i got it man , @BeepFelix thanks for this service , really appreciate your work <3
