### ISSUE TITLE
Unable to reuse previous accounts

### ISSUE THREAD

**Issue by yvm1995** [BeepFelix/csgo-commend-bot#118]
Hi Sir,
I tried using your commend bot and i was able to successfully get a few commends on my account however i am facing an issue
The accounts i use are generated from accgen.cathook.club and i am using 2 accounts at a time
Basically once i use these accounts i had received the 20 commends so after 9 hours i tried using them again after resetting the accounts list under database manager ..
In the cmd it says that the commends are successfully done like 20 commends done and 0 fail but i do not receive a single commend ..
My question is that is it possible to reuse a generated non prime account or do i need to commend using new accounts everytime
Looking forward to an answer

**Comment by BeepFelix** [comment]
One account cannot commend the same target twice.

Just like how you can't do it ingame. Hop in a casual game or something and try to commend someone, now try to commend the same person again, spoiler: You can't.

If you want 1000 commends you need 1000 accounts, you can't reuse accounts for the same target.

**Comment by yvm1995** [comment]
but then what about he cooldown .. say i use the same accounts after 24 hrs or even 2 days .. still im unable to commend the same target with the accounts .. so does it mean that once i have used a generated account to commend the target account it will never be able to commend it even after a certain time gap?

**Comment by BeepFelix** [comment]
You cannot commend the same target again ever. The cooldown is for *different* targets.

**Comment by yvm1995** [comment]
ok sir thank you .. also i am a noob with computers .. can you advice me how to mass create accounts using a proxy for accgen .. like how do i make a proxy and then use it

**Comment by BeepFelix** [comment]
No. Join the [accgen telegram group](https://t.me/sag_bot_chat) if you need help with such things or [ask on their GitLab](https://gitlab.com/nullworks/accgen/accgen-web/issues)
