### ISSUE TITLE
 Can you help with installation? 

### ISSUE THREAD

**Issue by nefesim20** [BeepFelix/csgo-commend-bot#120]
I get gyp errors in npm setup

![7](https://user-images.githubusercontent.com/56896962/67416514-a06c5380-f5cf-11e9-9a29-d965523ee5f6.JPG)

**Comment by BeepFelix** [comment]
Install NodeJS with Tools for Native Modules.

When installing check the box `Automatically install the necessary tools.`
![image](https://user-images.githubusercontent.com/22947557/67416875-eb826880-f5c7-11e9-913f-61647509af92.png)

**Comment by nefesim20** [comment]
I did what they said
This time he didn't solve the problem
![7](https://user-images.githubusercontent.com/56896962/67421767-d4e50d00-f5d9-11e9-8655-e599d26eb5bf.JPG)

**Comment by BeepFelix** [comment]
Okay so the issue here is you are using the latest v13 version, which doesn't have prebuilt binaries so it wants you to compile them yourself, which you can't. Install [this](https://nodejs.org/dist/v12.9.1/node-v12.9.1-x64.msi) Node version instead.

**Comment by nefesim20** [comment]
I'm trying now

**Comment by nefesim20** [comment]
npm installed I completed

So what do I do here?
![8](https://user-images.githubusercontent.com/56896962/67425239-517aea00-f5e0-11e9-951b-bb5f921f96ea.JPG)

**Comment by BeepFelix** [comment]
The [README](https://github.com/BeepFelix/csgo-commend-bot#database-manager) tells you everything you need to know.
