### ISSUE TITLE
Commeds account problem

### ISSUE THREAD

**Issue by nefesim20** [BeepFelix/csgo-commend-bot#121]
Hi, I have only one problem left,
how to add account
![9](https://user-images.githubusercontent.com/56896962/67429009-f1884180-f5e7-11e9-87e5-795dbb3d4800.JPG)

**Comment by nefesim20** [comment]
Will I find the account you are present in your link?

**Comment by BeepFelix** [comment]
You have to use your own accounts.

**Comment by nefesim20** [comment]
each account brings praise sooner?

**Comment by lnvades** [comment]
Could you please rephrase that? no one really understood what you said I'm pretty sure.

**Comment by nefesim20** [comment]
I don't have a bot account can you help?

**Comment by BeepFelix** [comment]
Make accounts, https://accgen.cathook.club/

**Comment by lnvades** [comment]
Just use generated accounts from accgen.cathook.club max per IP a day is 15 accounts.

**Comment by 2Eggsss** [comment]
> Just use generated accounts from accgen.cathook.club max per IP a day is 15 accounts.

You could also "potentially" bypass the IP limitations by utilizing a 4G mobile connection and turning off/turning on your data to change the IP address.

**Comment by nefesim20** [comment]
I'm gonna pay for these accounts, right?

**Comment by nefesim20** [comment]
Is it available for free

**Comment by lnvades** [comment]
Look at the site and find out yourself.

**Comment by nefesim20** [comment]
I am forced to Turkish is available for free?

**Comment by nefesim20** [comment]
sorry i tired you

**Comment by BeepFelix** [comment]
Just go to https://accgen.cathook.club/ and click generate.

**Comment by nefesim20** [comment]
thank you .!!
