### ISSUE TITLE
accgen.cathook.club

### ISSUE THREAD

**Issue by eizeize** [BeepFelix/csgo-commend-bot#124]
Hi, Is there a way to do this if you can't use https://accgen.cathook.club/ after 15 uses?

**Comment by nefesim20** [comment]
I'm tired of you! please help

**Comment by BeepFelix** [comment]
Account generator issues are not related to this project. I said if you have problems with the generator join [their Telegram](https://t.me/sag_bot_chat) and ask there or [ask on their Gitlab](https://gitlab.com/nullworks/accgen/accgen-web/issues).
