### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by brwekofc03** [BeepFelix/csgo-commend-bot#125]
whenever I tend to put npm install it appears
![ERRO](https://user-images.githubusercontent.com/56983902/67533528-aaaa5280-f6a0-11e9-95dd-85ff721e7daa.jpg)

**Comment by BeepFelix** [comment]
The issue here is you are using the latest v13 version, which doesn't have prebuilt binaries so it wants you to compile them yourself, which you can't. Install [this](https://nodejs.org/dist/v12.9.1/node-v12.9.1-x64.msi) Node version instead.
