### ISSUE TITLE
Npm Install Fail

### ISSUE THREAD

**Issue by FizzRaps** [BeepFelix/csgo-commend-bot#130]
**Npm Install keeps failing**

The commend bot worked for me but I reinstalled node.js & the commend bot and now "npm install" doesn't work anymore.

I've tried a lot of things, can someone help me?

![npm install](https://user-images.githubusercontent.com/57074702/67641019-d9bdff80-f8fe-11e9-8156-a8483b82ded8.png)

**Comment by BeepFelix** [comment]
The issue here is you are using the latest v13 version, which doesn't have prebuilt binaries so it wants you to compile them yourself, which you can't. Install [this](https://nodejs.org/dist/v12.9.1/node-v12.9.1-x64.msi) Node version instead.
