### ISSUE TITLE
How to fix a bug?

### ISSUE THREAD

**Issue by Art4ugan** [BeepFelix/csgo-commend-bot#132]
Climbs such an error
https://prnt.sc/ppkfcw
Even when the person on the server

**Comment by BeepFelix** [comment]
Config?

**Comment by Art4ugan** [comment]
{
	"commend": {
		"friendly": 120,
		"teaching": 120,
		"leader": 120
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/indie69/",
	"serverID": "{
	"commend": {
		"friendly": 120,
		"teaching": 120,
		"leader": 120
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"method": "SERVER",
	"target": "https://steamcommunity.com/id/indie69/",
	"serverID": "[A:1:71223303:13529]",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "E981B499732BB1F359571EB947558434"
}
",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "Evvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
}

**Comment by BeepFelix** [comment]
You showed your API key, reset it and generate a new one.

---

Your config seems fine, even though you copy pasted it here twice. I just changed something, try running it again and see if you get a proper error this time.

**Comment by Art4ugan** [comment]
https://prnt.sc/ppkyum

**Comment by BeepFelix** [comment]
The server you are trying to use is offline

**Comment by Art4ugan** [comment]
How to understand?

**Comment by BeepFelix** [comment]
Server is not working. Use a different `serverID`.

**Comment by sonicrules11** [comment]
Join a DM/Casual match and it should work fine

**Comment by Art4ugan** [comment]
They kick for afk, I need an old version of this script, is it there or how to find it?

**Comment by sonicrules11** [comment]
I don't know why you'd want an older version when the current works fine as I just used it mere minutes ago 

> They kick for afk

Go spectator.

> I need an old version of this script, is it there or how to find it?

Go back to an older commit
