### ISSUE TITLE
Sending only half of the commends

### ISSUE THREAD

**Issue by xselectx** [BeepFelix/csgo-commend-bot#133]
**Detailed bug description**
Console returning me no errors but sending only half. 
I mean "Chunk xx/xx finished with 20 successful commends and 0 failed commends"
But target get only half of the "successful" commends. If i set for example 10 commends to send, target get only 5 or sometimes even 0.

Yesterday i was receiving error 2, but today this happend.

**Error**
```
---
```

**Config**
```
{
	"commend": {
		"friendly": 325,
		"teaching": 325,
		"leader": 325
	},
	"account": {
		"username": "",
		"password": "",
		"sharedSecret": ""
	},
	"fetcher": {
		"username": "PrimeAccount",
		"password": "PrimePassword",
		"sharedSecret": "",
		"maxTries": 10,
		"tryDelay": 2500,
		"askSteamGuard": true
	},
	"method": "SERVER",
	"target": "https://steamcommunity.com/profiles/XXXXXX/",
	"serverID": "XXXX:XXXX",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 0,
	"steamWebAPIKey": "XX"
}

```

**Version**
- NodeJS: `v12.10.0`
- Script version: `2.2.5`

**Additional information**
Error starts occuring after yesterday steam update.

**Comment by BeepFelix** [comment]
#119
