### ISSUE TITLE
Suggestion: auto remove not working accounts

### ISSUE THREAD

**Issue by Craxto** [BeepFelix/csgo-commend-bot#136]
**Detailed question description**
is it possible to add a auto remove of not working accounts? It'S kinda getting annoying with "only" ~2500 accounts and manually removing like 400 bcuz they arent working :/

**Comment by BeepFelix** [comment]
Accounts which are not working are automatically ignored. It is irrelevant if you remove them or not.

**Comment by Craxto** [comment]
yea but i wanna clear my .txt file :D

**Comment by BeepFelix** [comment]
If you try to add accounts which are already in your database they will get ignored.

Simply don't remove any accounts from your database and it should work just fine.

**Comment by Craxto** [comment]
aight :( gotta have fun with my new 90k database :/
