### ISSUE TITLE
 too many commends are giving this error

### ISSUE THREAD

**Issue by brwekofc03** [BeepFelix/csgo-commend-bot#140]
![unknown](https://user-images.githubusercontent.com/56983902/68211670-bf4aec80-ffb6-11e9-8dcc-8253337bb181.png)

**Comment by BeepFelix** [comment]
What is your config? Follow the issue template.

**Comment by brwekofc03** [comment]
![unknown (1)](https://user-images.githubusercontent.com/56983902/68212473-5795a100-ffb8-11e9-9ee0-a735abfffa4e.png)

**Comment by BeepFelix** [comment]
Is the target on that server as well?

**Comment by Lefeo** [comment]
I get this problem often too.

And everytime the bot isnt logging in the last account. So if i have 20 acc. per chunk the bot is stopping at 19.

**Comment by BeepFelix** [comment]
> I get this problem often too.
> 
> And everytime the bot isnt logging in the last account. So if i have 20 acc. per chunk the bot is stopping at 19.

Happening on the last or last few is normal, but if it happens on almost all of them something is broken.

**Comment by brwekofc03** [comment]
yes the target is on the server

**Comment by BeepFelix** [comment]
Ah, I didn't look correctly. You're trying to do 40 at once. You can't. From my tests you seem to be able to do **at most** 20 per 5 minutes. So `perChunk` should be `20`.
