### ISSUE TITLE
I do not receive commned.

### ISSUE THREAD

**Issue by xSuspect** [BeepFelix/csgo-commend-bot#141]
**Detailed question description**
Hi I have a problem with the bot, it does not send (commends), and yet one does not send automatically (commends) and must be manually received every 5 minutes.(remains locked at 19 and no longer sends)
The steam profile is public.
https://prnt.sc/pssdqv
https://prnt.sc/pssh2i

**Config**
```
https://prnt.sc/pssut6
```
**Version**
- NodeJS: v12.12.0
- Script version: 2.2.5

**Comment by BeepFelix** [comment]
#119
