### ISSUE TITLE
Accounts timing out

### ISSUE THREAD

**Issue by tw0zh** [BeepFelix/csgo-commend-bot#143]
I am using everything as you said the accounts are timing out and when they used to work they worked only the first chunk.
![why](https://user-images.githubusercontent.com/26041065/68499666-a9a52380-0251-11ea-8684-528afcc3dcb9.png)

**Comment by BeepFelix** [comment]
Are you actually connected to the defined server as well?

**Comment by tw0zh** [comment]
Yes, still here
![yeap](https://user-images.githubusercontent.com/26041065/68499864-3ea81c80-0252-11ea-905d-d21db7f79699.png)

**Comment by BeepFelix** [comment]
Did it work before?

**Comment by tw0zh** [comment]
It worked only the first chunk then I waited and it doesn't go on.

**Comment by BeepFelix** [comment]
Interesting I am unsure why this could happen. Does it work if you manually cancel (`CTRL + C`) and restart?

**Comment by tw0zh** [comment]
I already tried that, I will try it again

**Comment by tw0zh** [comment]
It worked now but I bet the time between the chucks are 5 minutes right?

**Comment by BeepFelix** [comment]
According to the config in your screenshot the `betweenChunks` is 5 minutes, which is what worked when I tested it months ago. It could be that Valve has changed something.

**Comment by tw0zh** [comment]
I will wait and I will give a feedback here

**Comment by tw0zh** [comment]
nah doesn't work just like I said

**Comment by BeepFelix** [comment]
For testing purposes, if possible, lets try doubling it, change it from `300000` to `600000` and see if that works.

**Comment by tw0zh** [comment]
Done, waiting now...

**Comment by tw0zh** [comment]
Nope doesn't work

**Comment by BeepFelix** [comment]
Hmm, I am unsure what the cause or solution to this could be. Will wait to see if others have the same issue or not.

**Comment by tw0zh** [comment]
Alright

**Comment by tw0zh** [comment]
I think I figured out what the error is, don't know how to fix it tho.

In my console for the accounts it displays this
![this](https://user-images.githubusercontent.com/26041065/68502167-b167c680-0257-11ea-8fb7-0e58ca2d159b.png)

In this video it displays this
![video](https://user-images.githubusercontent.com/26041065/68502260-e4aa5580-0257-11ea-8686-16fb7a1c2150.png)

**Comment by BeepFelix** [comment]
Its typical to stop at 19 and get an error there, I am unsure why but it happens a lot, on the next chunk it should continue as normal.

**Comment by tw0zh** [comment]
Nope, I figured out the error. It's working fine now.
I had a space in the file that I imported to the database after removing it and reseting the database all works fine now, thanks!
