### ISSUE TITLE
SyntaxError??

### ISSUE THREAD

**Issue by pnrespawn** [BeepFelix/csgo-commend-bot#145]
What am I doing wrong?
![aripioare](https://user-images.githubusercontent.com/57761464/68865388-6c321180-06fb-11ea-991c-12b866f985b8.png)

**Comment by BeepFelix** [comment]
Your config is wrong, show your config.

Don't forget to censor sensitive information such as API key.

**Comment by pnrespawn** [comment]
> Your config is wrong, show your config.
> 
> Don't forget to censor sensitive information such as API key.

![123](https://user-images.githubusercontent.com/57761464/68865655-dd71c480-06fb-11ea-8cb0-f67571c9ad01.png)

**Comment by BeepFelix** [comment]
Why does target have an IP and a profile in it?

Target is your target, not the server.

**Comment by pnrespawn** [comment]
It`s working now, thank you!
