### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by PoliTry** [BeepFelix/csgo-commend-bot#147]
![Screenshot_5](https://user-images.githubusercontent.com/57819746/68986158-5d477e00-0825-11ea-8c01-925be0db1dff.png)
it stuck i wait 2 hours

**Comment by BeepFelix** [comment]
I know of a single other person who had this issue before and I couldn't figure out the problem. I don't know why this happens.

**Comment by mbello2** [comment]
ip block wait 2 hrs

**Comment by ZEROx45** [comment]
Just try with ur normal IP?

i had this issue by using/swapping proxies ~ while creating mass Accounts

**Comment by mbello2** [comment]
do not give 60 compliments with 1 ip then will put proxy and do 60 more and go

**Comment by BeepFelix** [comment]
You can't give more than 20 within 5 minutes anyways, and proxies don't change that as far as I know.

An IP limit would error and not stuck you.

**Comment by mbello2** [comment]
there is a valve limit which and 20 compliments for each send plus bulk send locks ip for 8 hours

**Comment by BeepFelix** [comment]
> bulk send locks ip for 8 hours

I've never heard of something like that nor did it happen to me.

**Comment by BeepFelix** [comment]
Someone re-download manually (Updater will not apply this update) and try out if this fixes your issue.

**Comment by xSuspect** [comment]
> Someone re-download manually (Updater will not apply this update) and try out if this fixes your issue.

apparently now works wonderfully ...(https://prnt.sc/q11tnj) (I tried this a few days ago but nothing)
thanks for the support !

**Comment by BeepFelix** [comment]
Alright, I will push the version then.

**Comment by xSuspect** [comment]
> Alright, I will push the version then.

what I noticed nudes sends in the game commends

**Comment by snareplug** [comment]
I had the same problem for long, updated now and still getting this

**Comment by snareplug** [comment]
quick update, made a delay of 7min and maximum of 18 commends per chunck it seems to work without this error, will update you

**Comment by UnbreakCode** [comment]
Timeout problem is still there. **Possible Fix would be to add Proxy Support to this since the IP will be blocked**. Testing it with new VPN Servers from NordVPN seems to work.

**Comment by ZEROx45** [comment]
i have it more hardly at LOGIN!!! method but server method went smooth for me :3

**Comment by BeepFelix** [comment]
> Timeout problem is still there. **Possible Fix would be to add Proxy Support to this since the IP will be blocked**. Testing it with new VPN Servers from NordVPN seems to work.
> 
> Already had added Proxy Support but I lost my files sadly. It was fixed after adding the support of proxies

I don't have a VPN to test this with but I will test some proxies when I get bored.

**Comment by BeepFelix** [comment]
Closing this, same issue as #156. Problem is most likely that the first account in your database is `NULL` as mentioned [here](156#issuecomment-562853449).
