### ISSUE TITLE
İs it vac reason?

### ISSUE THREAD

**Issue by Authetorke** [BeepFelix/csgo-commend-bot#150]
İs it vac reason ? First of sorry for my english level ? Unfortunately ı forget and use it in my main account now ım scaring about Vac problem is it reason of Vac?

**Comment by ziamrettop** [comment]
I am assuming that you think you can get VAC banned for using commendbot, the answer is no, you will not get banned for commendbotting, if it was bannable to commendbot we would commendbot pro players and get em banned? Thus VAC = Valve Allows Cheets...

**Comment by BeepFelix** [comment]
You could get banned, you most likely won't. The worst thing that would happen is Valve removes the botted commends.
