### ISSUE TITLE
NPM ERROR!!!

### ISSUE THREAD

**Issue by DuudeHD** [BeepFelix/csgo-commend-bot#151]
When I "npm install" there comes much errors and the commendbot doesnt work.I dont know how to fix this issue pls help
![Screenshot_14](https://user-images.githubusercontent.com/57959201/69170144-e1d21f00-0af9-11ea-9dc3-1e82de665fd1.png)
![Screenshot_15](https://user-images.githubusercontent.com/57959201/69170146-e3034c00-0af9-11ea-8575-2254902dbdc6.png)

I also installed Visual Studio 2017 and node.

**Comment by BeepFelix** [comment]
What is your `node -v` output?

**Comment by DuudeHD** [comment]
I will weiter Back when i am at Home okay could U pls write with me at 22 o
clock
Berlin time.

Isla <notifications@github.com> schrieb am Di., 19. Nov. 2019, 18:26:

**Comment by BeepFelix** [comment]
Just respond whenever you can. It doesn't matter, you can always reply.

**Comment by DuudeHD** [comment]
Im am back now and could u describe me how can i get the node -v output?

**Comment by DuudeHD** [comment]
Im back

Isla <notifications@github.com> schrieb am Di., 19. Nov. 2019, 18:30:

**Comment by BeepFelix** [comment]
As per readme, download Node version 12, dont use 13.

**Comment by DuudeHD** [comment]
You see my screenshot isnt it the right version 13.1.0 ?

**Comment by BeepFelix** [comment]
No, as I said. Uninstall it and download version 12.

**Comment by DuudeHD** [comment]
okay and how do i update the powsher node version
i got v.13 and want to downgrad to v12.

**Comment by BeepFelix** [comment]
As I said, uninstall your current node version and then download & install version 12.

**Comment by DuudeHD** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/57959201/69267826-3e9f0980-0bce-11ea-8df6-cfb9ddcf450d.png)
my  friend didnt get commends is there an issue?

**Comment by BeepFelix** [comment]
It clearly says Invalid Password, how would you expect to commend someone when you can't even log into the bot?

**Comment by DuudeHD** [comment]
Am I not logged in in the bot?

**Comment by 2Eggsss** [comment]
> Am I not logged in in the bot?
NO

**Comment by BeepFelix** [comment]
> Am I not logged in in the bot?

Read what the error says. You need Steam Accounts to use as bots so you can use them to commend someone. You can't just magically create commends.

**Comment by DuudeHD** [comment]
But I created accs on https://accgen.cathook.club/

**Comment by 2Eggsss** [comment]
> But I created accs on https://accgen.cathook.club/

Did you import them using the username:password file option?

**Comment by DuudeHD** [comment]
yes

**Comment by BeepFelix** [comment]
You imported it wrong then, such as an extra space or similar.

**Comment by DuudeHD** [comment]
NearLyingRook79:Quicktree19NRKBE76
RhetoricalShakySkunk66:Fuzzyspring369VZFN71
AlluringGapingEagle96:Bestworm53C4UNG10
SpitefulAfraidMagpie42:Darkrose596I7UL42
ScintillatingEndurableRail20:Cutewinter973G6A810
![Screenshot_19](https://user-images.githubusercontent.com/57959201/69268485-82ded980-0bcf-11ea-9c37-db5ef8b46e9f.png)

**Comment by BeepFelix** [comment]
Looks good to me, export the account list and see if there are any extra accounts in the list.

**Comment by DuudeHD** [comment]
how can i use the MatchID method 
"method": "SERVER",

**Comment by BeepFelix** [comment]
There is no MatchID method.

**Comment by DuudeHD** [comment]
![Screenshot_20](https://user-images.githubusercontent.com/57959201/69270072-8e7fcf80-0bd2-11ea-9d30-af3907cba5dd.png)
what is thath method ?

**Comment by DuudeHD** [comment]
MatchID can i use the Matchmaking id?

**Comment by BeepFelix** [comment]
1. Leave `matchID` at `"0"` its irrelevant
2. What you have as `matchID` right now is the `serverID`, you want it one above.
3. The `serverID` is wrong, as per README **only** the parts between the brackets and the brackets themselves are relevant: `[A:X:XXXXXXXXX:XXXXXX]:0` needs to be `[A:X:XXXXXXXXX:XXXXXX]`

**Comment by DuudeHD** [comment]
![Screenshot_21](https://user-images.githubusercontent.com/57959201/69270612-8e340400-0bd3-11ea-96ff-fd6c9a76cd88.png)
Server is full must it be on not a full server

**Comment by BeepFelix** [comment]
It clearly says it does need to be a non-full server.

**Comment by DuudeHD** [comment]
sry that was a dump question :)

**Comment by lnvades** [comment]
are you dumping your questions?

**Comment by 2Eggsss** [comment]
> are you dumping your questions?

get a better question resolver next time
