### ISSUE TITLE
How do I support 2fa?

### ISSUE THREAD

**Issue by CuriousGamerFTW** [BeepFelix/csgo-commend-bot#152]
![image](https://user-images.githubusercontent.com/29357534/69176478-b0f3e900-0afd-11ea-8358-6c986ea7c93b.png)

**Comment by BeepFelix** [comment]
Read the README. It says API Key, this has nothing to do with 2FA.

**Comment by CuriousGamerFTW** [comment]
What is the fetcher account? I cant find that in the readme file

**Comment by BeepFelix** [comment]
[Server ID](https://github.com/BeepFelix/csgo-commend-bot#server-id) mentions fetcher. You don't need it unless you use `auto`

**Comment by CuriousGamerFTW** [comment]
It is stuck on logging into the fetcher account.
I just want itto log into my accounts and report/commend the ID I give it. What do I need to change in the config

**Comment by BeepFelix** [comment]
The README tells you everything you need to know. If you have issues with the fetcher just don't use it and use normal server ID. Its not hard to use.
