### ISSUE TITLE
sqlite file??

### ISSUE THREAD

**Issue by chawik** [BeepFelix/csgo-commend-bot#158]
https://i.hizliresim.com/2Oz0NO.png

help please

**Comment by BeepFelix** [comment]
Did you do `npm install` like the README told you to?

**Comment by chawik** [comment]
first I ran as cmd administrator.
Secondly, I opened the file directory with cmd (with the command "cd").
Third, I wrote "npm install". Then I created config.json. Then I wrote databaseManager.js and got the error.

Translation can be bad, I've used google translation.

**Comment by BeepFelix** [comment]
Show what happened after you did `npm installl` or redo it.

**Comment by chawik** [comment]
https://i.hizliresim.com/9YZBQ3.png

I can solve this error using this command
npm --add-python-to-path='true' --debug install --global windows-build-tools

**Comment by BeepFelix** [comment]
You have NodeJS version 13 but you need version 12. Uninstall your current NodeJS version and [install version 12](https://nodejs.org/dist/v12.9.1/node-v12.9.1-x64.msi).

**Comment by chawik** [comment]
thx man <3 
Can I shoot a promotional video in Turkish?

**Comment by BeepFelix** [comment]
Sure

**Comment by chawik** [comment]
my e mail: sefagursel4114@gmail.com
write me please

**Comment by BeepFelix** [comment]
Why? You can just show how the bot is used and that's it?

**Comment by chawik** [comment]
okey man thanks 
FİXED
