### ISSUE TITLE
Commend Send

### ISSUE THREAD

**Issue by chawik** [BeepFelix/csgo-commend-bot#159]
ı have 25 account but program sending only 3 commend why?

**Comment by BeepFelix** [comment]
What do you mean? What does the console say? What happens in the game? What is your config? There is so much information missing.

**Comment by chawik** [comment]
https://i.hizliresim.com/anr7YO.png
https://i.hizliresim.com/YdZo6z.png

I uploaded 18 accounts to the database and tried to send it, but it didn't. When I tried several times, he only sent three of them, and the rest didn't.

**Comment by BeepFelix** [comment]
You ignored a part of my comment:

> What is your config?

If you want to send more at once then modify your config to do that.

**Comment by chawik** [comment]
https://i.hizliresim.com/jqbdAn.png
 ı am waiting 10 minutes

**Comment by BeepFelix** [comment]
I said config, not database manager.

**Comment by chawik** [comment]
ı am already fixed config

**Comment by BeepFelix** [comment]
According to what you said: You want to send more commends at once.

According to your screenshot (https://i.hizliresim.com/YdZo6z.png): Your config is set to only send 3 at once, so change the number in your `config.json`.

What you currently have is expected behavior.

**Comment by chawik** [comment]
ı fixed man sorry. You have account  list

**Comment by BeepFelix** [comment]
No, use [accgen.cathook.club](https://accgen.cathook.club/), for help [**join their Telegram**](https://t.me/sag_bot_chat).
