### ISSUE TITLE
[Suggestion] Optional Command Line Arguments

### ISSUE THREAD

**Issue by TheRhanderson** [BeepFelix/csgo-commend-bot#16]
Would it be possible to create an option to reverse (remove) the commends of a certain profile? For example:

node remove-cmds.js profile amount

**Comment by BeepFelix** [comment]
Certainly is, I will start working on it tomorrow or later when I get time.

**Comment by BeepFelix** [comment]
Added experimental uncommend here: https://github.com/BeepFelix/csgo-commend-bot/commit/152eec53e606e6299fe696bc0787085543adfc15

I didn't test it a lot but I think it should work.

**Comment by TheRhanderson** [comment]
I'll try today as soon as the accounts I've used are available again. For now, thank you!

**Comment by TheRhanderson** [comment]
Hello there, here's my feedback.

index_undoCommends.js aren't checking the "lastCommend" property. I've tried removing 100 commends from a profile in which I'll call it "steamID64". I've tried two ways:

1.

>  node index_undoCommends.js

— I edited the profile and commend-to-remove inside config_undoCommends.json

2. 

> node index_undoCommends.js <steamid> <value>

— I entered the profile and the amount directly into the command.

Both resulted in:

> Parsing account from "steamID64"
> Successfully parsed account to "steamID"
> Getting 100 already used accounts
> 0/100 accounts available but we need 100 accounts

Yes, the "lastCommend" is set to " -1 " and the accounts are ready to send commends.

**Comment by BeepFelix** [comment]
It very much checks the lastCommend property `(new Date().getTime() - a.lastCommend) >= config.AccountCooldown`, else we would just get limited again.

And obviously you can only uncommend with accounts which have already commended so there is a check in for that aswell `a.commended.includes(config.AccountToCommend)`.

Make sure the AccountID of the user you want to uncommend is still in the `commended` array of the accounts.

**Comment by TheRhanderson** [comment]
Yes, same here... the commends were not removed.

In https://steamcommunity.com/id/my/gcpd/730/?tab=playercommends — I checked through the account I tried to remove, and the site indicates that the operation was done with the options cleared. It was supposed to work. But apparently it didn't work. Weird ;(

**Comment by TheRhanderson** [comment]
I'll try later putting those options in 'false' and resubmit using index.js to see what happens.

https://imgur.com/a/TG1IuN0

**Comment by TheRhanderson** [comment]
Feedback:

It worked! I changed the options below to 'false':

> 	"Commend": {
> 		"Friendly": false,
> 		"Teacher": false,
> 		"Leader": false
> 	}

**Comment by TheRhanderson** [comment]
> It very much checks the lastCommend property `(new Date().getTime() - a.lastCommend) >= config.AccountCooldown`, else we would just get limited again.
> 
> And obviously you can only uncommend with accounts which have already commended so there is a check in for that aswell `a.commended.includes(config.AccountToCommend)`.
> 
> Make sure the AccountID of the user you want to uncommend is still in the `commended` array of the accounts.
> 
> EDIT: The thing that confuses me is that I had someone previously tell me that they can successfully remove commends from someone and I tried it myself on a friend legitimately using the ingame function and it did work, but with the bots it doesn't seem to work. I tried to remove some commends from myself just now but it did absolutely nothing.
> 
> EDIT 2: Literally went through 500+ bots and tried to remove all of their commends.. Nothing changed.
