### ISSUE TITLE
Constant timeouts

### ISSUE THREAD

**Issue by dwnhauhdwnuhd** [BeepFelix/csgo-commend-bot#160]
So soon as i start commending someone, i get red and green error saying something about commending, I dont know  how to fix this.

**Comment by BeepFelix** [comment]
Show the error.

**Comment by dwnhauhdwnuhd** [comment]
https://gyazo.com/3a06249cb47531fa94de946c635adbe3

**Comment by BeepFelix** [comment]
And how does your config look like?

**Comment by dwnhauhdwnuhd** [comment]
https://gyazo.com/dbde02b058aed2b439651250914ae0e9

**Comment by BeepFelix** [comment]
Your cooldown is *very* low, its likely the same bots are being used which are currently on cooldown and unable to commend and other than that these are possible reasons for your error too: https://github.com/BeepFelix/csgo-commend-bot/issues/149#issuecomment-554678453

**Comment by dwnhauhdwnuhd** [comment]
I havnt used this commend bot in weeks, that cant be it.

**Comment by BeepFelix** [comment]
Other than the reasons listed I don't know what could be the reason. Other than that this is basically a duplicate of #149
