### ISSUE TITLE
Stopped working.

### ISSUE THREAD

**Issue by visark** [BeepFelix/csgo-commend-bot#163]
The bot stopped working, I deleted the file from my C drive. 
Installed it again. Removed example from config file. 
typed in 
cd -thedirectoryofthebot-
then npm install and it gave me this
npm install
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by BeepFelix** [comment]
You don't have NodeJS installed.

**Comment by visark** [comment]
![1234](https://user-images.githubusercontent.com/58346235/69891378-2f087a80-12ca-11ea-9f4e-eb554a22adc7.png)

**Comment by visark** [comment]
The weird thing is it was working before, and I haven't removed anything. Tried running it and no luck.

**Comment by BeepFelix** [comment]
[As per Google](https://stackoverflow.com/a/21923238):

> Just add:
> `;C:\Program Files\nodejs\`
> To the end of your Path variable on the "User variable" section of the Environment Variables on the System Properties.
> 
> After that, reopen your command prompt and type
> `npm`
> This should work.

**Comment by visark** [comment]
Uninstalled node,js and installed it. It works just fine now. Thanks so much for your help.
Thanks again much love.
