### ISSUE TITLE
add a feature to remove all not working accounts.

### ISSUE THREAD

**Issue by Rootzi** [BeepFelix/csgo-commend-bot#164]
would be very useful for having lots of not working accounts.

**Comment by BeepFelix** [comment]
This has no use, accounts not working will not be used.

**Comment by Rootzi** [comment]
but if they are vac'd then it still counts them in the chunk, you have to wait a long time to finally get working commends from non banned accounts

**Comment by BeepFelix** [comment]
They don't, *or at least shouldn't*. If an account is banned or in any way unusable it will mark it as such and never use the account again. They will not be touched in any way ever again.
