### ISSUE TITLE
Patched?

### ISSUE THREAD

**Issue by csirketorta** [BeepFelix/csgo-commend-bot#169]
**Detailed question description**
Is it patched? I have tried commendbotting myself on 3 different gameservers (valve official mm, self-hosted csgo server, and offline with bots server). I kept getting the "you have got a commend" message in the chat, but my commend stood on 443 (i got them a month ago or 2)

**Config**
https://pastebin.com/5U3gSGb4

**Version**
I have been using the LTS nodejs and the latest script from github.

2 pictures from ingame and the cmd. https://imgur.com/a/Q30Zbp1

**Comment by BeepFelix** [comment]
Same as #119. I don't know why this happens. CSGO gives a success response and you even get a notification in-game, no idea why it doesn't increase the number though.
