### ISSUE TITLE
Failed to login due to proxy timeout

### ISSUE THREAD

**Issue by erudzitis** [BeepFelix/csgo-commend-bot#171]
Tried with different proxies, made sure that their type is http and that they are fast. Used default settings, everything works without proxies.

**Error**
```
https://cdn.discordapp.com/attachments/645559220871364608/653316170338009088/prox.png
```

**Config**
```
https://imgur.com/a/qgA1G7P
```

**Version**
- NodeJS: `v12.9.1` (You can find this using `node -v`)
- Script version: `2.4.0`

**Additional information**
Add any other potentially useful information about your issue here.

**Comment by BeepFelix** [comment]
Steam might be blocking your proxies

**Comment by erudzitis** [comment]
> Steam might be blocking your proxies

Could you provide me some vendors or a way where you get proxies that aren't blocked by steam?

**Comment by BeepFelix** [comment]
I cannot because I don't know any.

**Comment by SpaceR3** [comment]
> > Steam might be blocking your proxies
> 
> I cannot because I don't know any.

I bought 1gb proxy (rotating) for 3$ (it is not blacklisted by steam I checked manually) and i still get that error
