### ISSUE TITLE
Powershell error

### ISSUE THREAD

**Issue by PedroLima14** [BeepFelix/csgo-commend-bot#19]
When i do npm install in PowerShell, this error happens:

npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm install
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by BeepFelix** [comment]
Did you install NodeJS and what version (`node -v`)?
