### ISSUE TITLE
Whats this error?

### ISSUE THREAD

**Issue by caiovrcombat** [BeepFelix/csgo-commend-bot#20]
Microsoft Windows [versão 10.0.17134.523]
(c) 2018 Microsoft Corporation. Todos os direitos reservados.

C:\Users\User>cd c:\CaioVillar - Arquivos\Caio Villar\Jogos\Counter-Strike Global Offensive\Programas\csgo-commend-bot-master

c:\CaioVillar - Arquivos\Caio Villar\Jogos\Counter-Strike Global Offensive\Programas\csgo-commend-bot-master>node index.js STEAM_0:1:462159782 50
c:\CaioVillar - Arquivos\Caio Villar\Jogos\Counter-Strike Global Offensive\Programas\csgo-commend-bot-master\index.js:42
(async () => {
       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

c:\CaioVillar - Arquivos\Caio Villar\Jogos\Counter-Strike Global Offensive\Programas\csgo-commend-bot-master>

**Comment by BeepFelix** [comment]
Update your [NodeJS](https://nodejs.org/).

**Comment by caiovrcombat** [comment]
> Update your [NodeJS](https://nodejs.org/).

to 11.7?

**Comment by caiovrcombat** [comment]
> Update your [NodeJS](https://nodejs.org/).

Tks!!! Sucessfully

**Comment by caiovrcombat** [comment]
THE BEST COMMEND/REPORT BOT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by caiovrcombat** [comment]
Can you codding a Steam Account Generator?

**Comment by BeepFelix** [comment]
No.
