### ISSUE TITLE
Is this a fixed time? Can I try to change it?

### ISSUE THREAD

**Issue by Whooopss** [BeepFelix/csgo-commend-bot#27]
AccountCooldown: Description: How long accounts are on cooldown before they can be reused. Currently 12 hours.
RateLimitedCooldown: Description: The time in milliseconds how long we should wait incase we hit a ratelimit. I recommend ~1 hour.

**Comment by BeepFelix** [comment]
`AccountCooldown` is from other players years ago already testing that. Its a limit set by Valve. You can change it but its useless to change it. The option is there incase it ever changes.

`RateLimitedCooldown` is just a random number I came up with. You only get ratelimited by Steam for logging in too much. And those ratelimits are very long. I waited 3 hours at one time. You can change it freely but you shouldn't really hit any ratelimit anyways.
