### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by thekaway404** [BeepFelix/csgo-commend-bot#28]
Hello, my problem is in the proxies

I put the proxies like this, right?
"Proxies": ["168.195.171.42:44880"]

But I get error

TypeError [ERR_INVALID_PROTOCOL]: Protocol "168.195.171.42:" not supported. Expected "http:"

**Comment by BeepFelix** [comment]
Read the error.

Prefix it with `http://`.

`168.195.171.42:44880` > `http://168.195.171.42:44880`

**Comment by thekaway404** [comment]
Thanks, fix now
