### ISSUE TITLE
He can show , witch accs are banned / have cooldown / not work?

### ISSUE THREAD

**Issue by FuNTeX** [BeepFelix/csgo-commend-bot#3]
Hey mate
can u add that?
i see only red staff

but more Informationen are better for me :D

=)

**Comment by BeepFelix** [comment]
If you are banned from CSGO you will never get a response from the GameCoordinator in the first place. [I still have to add a timeout error for that](https://github.com/BeepFelix/csgo-commend-bot/blob/60720a76e029c4ad18c3803213085ba9f5ad5168/helpers/account.js#L75).

If you are on commend-cooldown you will get a timeout error, but usually that should never happen as the commend bot respects that and waits 12 hours before reusing another account.

If you fail to login the value of "operational" will be a number, the number represents one of [these](https://github.com/DoctorMcKay/node-steam-user/blob/master/enums/EResult.js) login errors. If a unknown error occurred it will just be "false".

**Comment by Mike129812** [comment]
Can't each account commend 3 people before having to wait 12/24 hours?

**Comment by BeepFelix** [comment]
Its different when you do it legitimate, I don't know why or how it differentiates bot-commends from real-commends but it does.
