### ISSUE TITLE
Suggestion: get latest commend time

### ISSUE THREAD

**Issue by nardow** [BeepFelix/csgo-commend-bot#32]
maybe an arg that shows the last commend/report time?

**Comment by BeepFelix** [comment]
The issue is, with lots of accounts. Which time do you write? All accounts have a different time.

**Comment by nardow** [comment]
i guess that returning the latest timestamp would give us a good idea of when we will be able to use the accs again. imagine this: we bot with x accs, after some time we run the script again but the accs are still on cooldwon, so we enter a command/run the script with an arg that returns the timestamp of the latest commend/report.
or maybe, let's say we want to bot with 15k accs but only 10k out of 15k are available, so we run this command and it gets all the _"less recent"_ timestamps of the accounts necessary to bot with 15k and returns the _"most recent"_ one, feel me?

**Comment by cybergodjsp** [comment]
create a simple .db database file with node.js read/write/update fast/east updating account info for massive importing/exporting and updating time/usage.

**Comment by BeepFelix** [comment]
I still have plans to make this work, I just have to think of a good way of displaying it.

**Comment by xShany** [comment]
Will you be adding the reportbot back to the master-branch?

**Comment by BeepFelix** [comment]
No

**Comment by Falghere** [comment]
So RIP rbot?
Do you know of any RBOT that currently works and is free or is there any chance you can do an update on yours?

**Comment by BeepFelix** [comment]
You can use the [Legacy Version](https://github.com/BeepFelix/csgo-commend-bot/tree/legacy) for report botting.

**Comment by Falghere** [comment]
Does this still work?

**Comment by BeepFelix** [comment]
Try it out. Valve said report bots are patched. Nobody has any proof that they actually work, so who cares.

**Comment by Falghere** [comment]
I already tried...it does not seem to be working...

there's no way you can take a look at it and see if anything can be improved?

I saw a galley using server id to report only on rbot payments

**Comment by BeepFelix** [comment]
I am not going to bother with report bots. I believe they are fixed and I don't even meet any cheaters to test it out with.

**Comment by crx9** [comment]
> I am not going to bother with report bots. I believe they are fixed and I don't even meet any cheaters to test it out with.

report bot is useful ，when i met the spinbot cheaters,I Sent 1000+ ,they r always banned in an hour

**Comment by BeepFelix** [comment]
I am not gonna argue on an issue thread totally unrelated to reporting. Point is I am not gonna so it unless there is 100% evidence they work and you physically cannot do this.

**Comment by Jaeger33211** [comment]
Many of the Reportbotted Players get into Overwatch. (Thanks for your ow-bot ^^). If anyone wants the Reportbot with db support just message me.

**Comment by JekProGamer** [comment]
ставлю 209 аккаунтов и мне пишет постоянно timout из 209/100 не работает http://prntscr.com/otec5w

**Comment by BeepFelix** [comment]
> ставлю 209 аккаунтов и мне пишет постоянно timout из 209/100 не работает http://prntscr.com/otec5w

- English only
- Create your own issue thread [here](https://github.com/BeepFelix/csgo-commend-bot/issues/new)

**Comment by JekProGamer** [comment]
put 209 accounts and wrote to me constantly from 209/100 timout not working http://prntscr.com/otec5w

**Comment by JekProGamer** [comment]
put 209 accounts and wrote to me constantly from 209/100 timout not working http://prntscr.com/otec5w

**Comment by BeepFelix** [comment]
> ставлю 209 аккаунтов и мне пишет постоянно timeout из 209/100 не работает http://prntscr.com/otec5w

- English only
- Create your own issue thread [here](https://github.com/BeepFelix/csgo-commend-bot/issues/new)

**Comment by xSuspect** [comment]
you still have a reportbot that I can't find ?

**Comment by BeepFelix** [comment]
Report bots are fixed.

You can always go back in commit history and look at the old code. The very old one included a report bot, you can go back in history and find it.
