### ISSUE TITLE
has been like this for 12 hours

### ISSUE THREAD

**Issue by beepboop115** [BeepFelix/csgo-commend-bot#34]
![image](https://user-images.githubusercontent.com/47283079/52169017-15da8000-2732-11e9-9dfa-71ca504406ed.png)

**Comment by BeepFelix** [comment]
Use a different Steam API Key. I can't go around a steam limitation. The only other option you have is directly using AccountID instead of SteamID. That way Steam Web API does not get used.

**Comment by beepboop115** [comment]
Ive tried using a different Steam API key, still doesn't seem to work

**Comment by BeepFelix** [comment]
Steam limiting you, nothing I can do. Use AccountID instead of SteamID, if I remember correctly it doesn't require Steam Web API

**Comment by beepboop115** [comment]
Where can I find the AccountID

**Comment by BeepFelix** [comment]
[Readme](https://github.com/BeepFelix/csgo-commend-bot#account-to-commend)

Use a website like [SteamID.io](https://steamid.io) to get the SteamID3, everything after the second colon is the account id.

**Comment by beepboop115** [comment]
fixed the issue thank you
