### ISSUE TITLE
Errors?

### ISSUE THREAD

**Issue by Pruzz1** [BeepFelix/csgo-commend-bot#39]
![error](https://user-images.githubusercontent.com/47386975/52341570-db8b1e80-2a62-11e9-9de1-ff3b13db9c18.png)
Was Working fine last night not working with gitbash or powershell anymore.

**Comment by BeepFelix** [comment]
>`parseAccountList.js`
>`node parseAccountList.js`

Hmm...

**Comment by Pruzz1** [comment]
> > `parseAccountList.js`
> > `node parseAccountList.js`
> 
> Hmm...
would agree i am pretty fucking retarded lul
