### ISSUE TITLE
[SUGGESTION] Proxy support on Timeout

### ISSUE THREAD

**Issue by idontneedhelp** [BeepFelix/csgo-commend-bot#4]
A Proxy support against the timeout would be nice

**Comment by BeepFelix** [comment]
Timeouts are not related to IP limits, they are related to already having someone commended within the past 12 hours or connection issues.

Though you can use proxies to go around the login-limit Steam puts upon you. I will take a look and see if it works.

**Comment by idontneedhelp** [comment]
yeah i meant the ratelimit

**Comment by idontneedhelp** [comment]
Do u mind if u let me know how u wanna do it? 
With the http module or with the included steamcmclient proxy support?

**Comment by BeepFelix** [comment]
I thought about doing it [this way](https://dev.doctormckay.com/topic/1160-use-proxy/). Though all the public proxies I tried just returned an error and didn't work at all. Since then didn't revisit the issue.

**Comment by cybergodjsp** [comment]
getproxylist.com has small pool of IPs.
