### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by sdsdfrdsgfdgfd** [BeepFelix/csgo-commend-bot#42]
**Sometimes work, sometimes doesn't.**
I can login in the accounts (in my pc), but the script tells me that: 
![image](https://user-images.githubusercontent.com/31171165/52527482-01156380-2cc1-11e9-8667-26db39da9430.png)
When i use others bots, that accounts work... **what is the problem?**

**Comment by BeepFelix** [comment]
The password is wrong, thats whats up. What characters are in your password? Only A-Z and 0-9 or some special characters aswell?
