### ISSUE TITLE
cannot find module "steam"

### ISSUE THREAD

**Issue by ImLauge** [BeepFelix/csgo-commend-bot#43]
![image](https://user-images.githubusercontent.com/46719124/52527858-dbdc2180-2ccf-11e9-8a77-0553498fcbee.png)

**Comment by ImLauge** [comment]
![image](https://user-images.githubusercontent.com/46719124/52527878-6b81d000-2cd0-11e9-944c-66c6a267900b.png)

**Comment by r4nd0wn** [comment]
have you done npm install ?

**Comment by ImLauge** [comment]
I'm retarded, let's pretend this question never happened.
