### ISSUE TITLE
Script being terminated after the following line

### ISSUE THREAD

**Issue by focks95** [BeepFelix/csgo-commend-bot#45]
Parsing account from https://steamcommunity.com/id/*******/
Successfully parsed account to 9******
Getting 1 account
0/1 account available but we need 1 account

C:\Users\Admin\Desktop\commend\commend>
C:\Users\Admin\Desktop\commend\commend>node index.js
Parsing account from https://steamcommunity.com/id/*******/
Successfully parsed account to *********
Getting 5 accounts
0/1 account available but we need 5 accounts

**Comment by BeepFelix** [comment]
0 accounts available... You can't really commend anyone if you have no accounts available.

**Comment by focks95** [comment]
What does that even mean?

**Comment by BeepFelix** [comment]
You have no accounts available.

**Comment by focks95** [comment]
I'm sorry for being so dumb but that means all the bots are used up? or do i have to do something?

**Comment by BeepFelix** [comment]
Basically but you only have 1 bot in your accounts.json.....

**Comment by focks95** [comment]
Yes, i did change that because the number of available bots were 1 or 2, So i wanted to check what happens.

**Comment by BeepFelix** [comment]
You are on cooldown or already commended the person you are trying to commend.
