### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Art4ugan** [BeepFelix/csgo-commend-bot#48]
![image](https://user-images.githubusercontent.com/47487193/52797005-faeb0280-3085-11e9-8fc7-80bde8dfdcd3.png)

**Comment by BeepFelix** [comment]
Your accounts.json is fucked

**Comment by Art4ugan** [comment]
> Твой аккаунт

It is necessary to throw, I just Russian and Google does not translate well

**Comment by BeepFelix** [comment]
The file `accounts.json` has an error in it. Its corrupted.
