### ISSUE TITLE
Error to send commend HELP ME!

### ISSUE THREAD

**Issue by OGTvGaming** [BeepFelix/csgo-commend-bot#52]
I have this error what happend?    
`Error: Failed to send commend: Timeout
    at Timeout.setTimeout [as _onTimeout] (csgo-commend-bot-master\helpers\account.js:137:12)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)`

**Comment by sebastiandev19** [comment]
Commend fixed by valve.

**Comment by OGTvGaming** [comment]
okay
but the same mistake I have with the reportbot   :/

**Comment by sebastiandev19** [comment]
The accounts has a delay of 24hrs, if u reportbotted with the same acc u need to wait 24hrs.

**Comment by BeepFelix** [comment]
>Failed to send commend

Commend bots are currently fixed but a bypass is being worked on. If you have issues with the commend bot at the moment please use #50
