### ISSUE TITLE
Add a queue list for reporting?

### ISSUE THREAD

**Issue by 123top** [BeepFelix/csgo-commend-bot#53]
Just an idea, so we have a list with people to report bot.

**Comment by BeepFelix** [comment]
First of all [this](https://www.reddit.com/r/GlobalOffensive/comments/89qk3l/i_emailed_a_valve_employee_about_csgo_and_got_a/dwtqe94/) but some people say its bullshit, personally don't think it is. Otherwise, just run `node index_report.js` after changing the config? :thinking:

**Comment by 123top** [comment]
I know about that thing on reddit, but it seems like if I don't spam reports (50 at one time) and instead report with a smaller number I got a very high success rate. I am changing cfg and run it again, just thought a queue would be pretty usefull.

**Comment by 123top** [comment]
I know about that thing on reddit, but it seems like if I don't spam reports (50 at one time) and instead report with a smaller number, but report every x minutes, I got a very high success rate. I am changing cfg and run it again, just thought a queue would be pretty usefull.

**Comment by idontneedhelp** [comment]
Just use a Database to report someone.
Then you do node "addtodb.js steamid"
And the user gets inserted into database after that u can work the que

**Comment by despa1r1337** [comment]
ur report bot dont work :3 im testing, no banned.
1 day- no banned (wh+bhop+aim) + match id
2 day- no banned (semi rage) + match id
3 day- banned (ragebot) (ragebot banned automatically by system)

**Comment by BeepFelix** [comment]
> ur report bot dont work :3 im testing, no banned.
> 1 day- no banned (wh+bhop+aim) + match id
> 2 day- no banned (semi rage) + match id
> 3 day- banned (ragebot) (ragebot banned automatically by system)

Report bots haven't worked for months if you actually read what Valve wrote [here](https://www.reddit.com/r/GlobalOffensive/comments/89qk3l/i_emailed_a_valve_employee_about_csgo_and_got_a/dwtqe94/).

**Comment by despa1r1337** [comment]
zonerbot.xyz 
how it worked, and it works, strange, yes? Now would believe the words VALVE

**Comment by BeepFelix** [comment]
> zonerbot.xyz
> how it worked, and it works, strange, yes? Now would believe the words VALVE

Yes because reporting an obvious cheater is retarded. VACNet will get that guy anyways. And if you report a legit cheater Overwatch won't catch them anyways.

**Comment by despa1r1337** [comment]
> > zonerbot.xyz
> > how it worked, and it works, strange, yes? Now would believe the words VALVE
> 
> Yes because reporting an obvious cheater is retarded. VACNet will get that guy anyways. And if you report a legit cheater Overwatch won't catch them anyways. There is absolute zero reason to even report bot anymore.


![image](https://user-images.githubusercontent.com/48297813/54076198-df0c0280-42b9-11e9-8180-488005cc37a2.png)

"obvious cheater is retarded"

**Comment by BeepFelix** [comment]
Are you trying to tell me that because someone got banned its totally the report bot which is the reason behind it?

If they can restrict commend bots to ONLY work if you are on a specific server then they can obviously also do that with report bots.

And while they are at it, why not ignore community reports and only care about reports done in a official match, oh shit wait they can use the GC to actually check if you are assigned to the same match as the person you are trying reporting.

You have to be obvious enough to get Overwatch banned as it is already and that is also easily enough for VACNet to catch is as well.

Someone got banned, how spooky. What proves that its because you report botted them? Nothing.

**Comment by MikhaelLauda** [comment]
Ahahaha, just close this section
Stubborn kids don't know about the system and try to argue with coder

**Comment by despa1r1337** [comment]
> Ahahaha, just close this section
> Stubborn kids don't know about the system and try to argue with coder

no one spoke to you, just shut up

**Comment by BeepFelix** [comment]
> Ahahaha, just close this section
> Stubborn kids don't know about the system and try to argue with coder

Frankly, just because I write this doesn't mean I know if it works or not. I just leave it at: I have my own opinion on the topic, they have theirs.
