### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by inieuwoudt1** [BeepFelix/csgo-commend-bot#54]
After all the installation steps was done correctly, running this command shows me this error.
I tried using different API's from different accounts as well.

`
node index_report.js 76561198114346529 50
Parsing account from 76561198114346529
<html><head><title>Forbidden</title></head><body><h1>Forbidden</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>
Malformed Steam API Response
`

**Comment by BeepFelix** [comment]
Read the error. Your config.json has no `SteamAPIKey` defined

**Comment by inieuwoudt1** [comment]
I do have an API defined. Inside the config,json: "SteamAPIKey": "CFF4E701D5CB5DA92C47D399--------",

**Comment by BeepFelix** [comment]
Then its invalid or wrong

**Comment by inieuwoudt1** [comment]
You were right. Did not know I had to specify it inside 'config_report.json' instead of 'config.json'.
Sorry and thank you.
