### ISSUE TITLE
Failed to find protobufs, downloading and extracting...

### ISSUE THREAD

**Issue by Baston1337** [BeepFelix/csgo-commend-bot#62]
![Screenshot_2](https://user-images.githubusercontent.com/51772547/59565416-d13cea80-9029-11e9-9749-678e219f8cbb.png)

**Comment by BeepFelix** [comment]
Make sure **nothing** is accessing the `protobufs` folder and try again

**Comment by Baston1337** [comment]
He downloaded the protobufs with -master, just renamed and worked.
