### ISSUE TITLE
Invalid Regular Expression after node index.js

### ISSUE THREAD

**Issue by Seikusu** [BeepFelix/csgo-commend-bot#63]
![Capture](https://user-images.githubusercontent.com/25873463/59570531-fda54500-90c3-11e9-9335-b60181db39bb.JPG)

**Comment by BeepFelix** [comment]
What NodeJS version are you running? `node -v`

**Comment by Seikusu** [comment]
$ node -v                                                                        v8.11.3
--

**Comment by BeepFelix** [comment]
Very old, you should update [NodeJS](https://nodejs.org/) to a newer version.

**Comment by Seikusu** [comment]
Thank you very much! , it worked now, i didnt check the version , sorry .
