### ISSUE TITLE
Erro Npm Install Csgo Commend Bot

### ISSUE THREAD

**Issue by haadeck** [BeepFelix/csgo-commend-bot#64]
https://imgur.com/a/jrHDf2F

Csgo Commend Bot experimental

help me

**Comment by BeepFelix** [comment]
What node version do you have `node -v`

**Comment by haadeck** [comment]
v12.4.0

**Comment by haadeck** [comment]
I tested it with v 10 plus it did not work

**Comment by BeepFelix** [comment]
I have no idea what this error means or how to fix it. Google gives a bunch of different answers for very old versions as well. I guess just try to Google it and see what helps out of the responses.

**Comment by haadeck** [comment]
okay thx

**Comment by haadeck** [comment]
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/protobufjs/protobuf.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by BeepFelix** [comment]
[Install GIT](https://git-scm.com/downloads)

**Comment by BeepFelix** [comment]
I assume this issue has been resolved.
