### ISSUE TITLE
Npm Error

### ISSUE THREAD

**Issue by EGTLoneWolf** [BeepFelix/csgo-commend-bot#65]
![image](https://user-images.githubusercontent.com/37926526/60374430-ff152c80-9a36-11e9-8a76-c2dcfe819331.png)

![image](https://user-images.githubusercontent.com/37926526/60374415-e73da880-9a36-11e9-88df-4750580fde4e.png)

How to fix this error?

**Comment by Jaeger33211** [comment]
Install Git and add it to Path

**Comment by EGTLoneWolf** [comment]
Finished (fixed)
