### ISSUE TITLE
Failed to send message: Timeout yyyeeaaaa help

### ISSUE THREAD

**Issue by DatBoiBaku** [BeepFelix/csgo-commend-bot#68]
![image](https://user-images.githubusercontent.com/45308130/61111563-8a101100-a492-11e9-8453-e1af9d108855.png)
probs something with the GameCoordinator.js idk

**Comment by DatBoiBaku** [comment]
i guess i have another pc and go long into the bot account there, go into a party, go on official servers, commend myself, quit and repeat
it's long but better than nothing i guess

**Comment by BeepFelix** [comment]
This is not an issue with the bot itself. It either with you sending commends too fast, too many in a short amount of time.

**Comment by DatBoiBaku** [comment]
> This is not an issue with the bot itself. It either with you sending commends too fast, too many in a short amount of time.

then what do?

**Comment by BeepFelix** [comment]
Did the previous ones work or did all of them fail?

**Comment by DatBoiBaku** [comment]
> Did the previous ones work or did all of them fail?

all since downloaded the bot

**Comment by BeepFelix** [comment]
My question was related to 19/20 or 15/20. Did those work?

**Comment by DatBoiBaku** [comment]
> My question was related to 19/20 or 15/20. Did those work?

nope, same errors (if i'm thinking correctly what you are asking me)

**Comment by BeepFelix** [comment]
`LOGIN` or `SERVER` method?

**Comment by DatBoiBaku** [comment]
> `LOGIN` or `SERVER` method?

didn't try yet, brb, it's on server rn

**Comment by BeepFelix** [comment]
If its on server, did you correctly fill in the `serverID` and also connect to the right server?

**Comment by DatBoiBaku** [comment]
now all my 40 account i had rn are now wasted and i gotta wait 8 hours :') welp

**Comment by BeepFelix** [comment]
You could wipe the database and just readd the accounts.

**Comment by DatBoiBaku** [comment]
> If its on server, did you correctly fill in the `serverID` and also connect to the right server?

i didn't do both lmao

**Comment by DatBoiBaku** [comment]
> You could wipe the database and just readd the accounts.

lmao what k brb

**Comment by DatBoiBaku** [comment]
YOOOO IT WORKS thanks!
