### ISSUE TITLE
Not working commend bot

### ISSUE THREAD

**Issue by wiktor000** [BeepFelix/csgo-commend-bot#69]
`S C:\Users\Wiktor\Desktop\csgo-commend-bot-legacy> node index
Parsing account from https://steamcommunity.com/profiles/76561198951927206
Successfully parsed account to 991661478
Getting 3 accounts
[UnbecomingManyLevelMongoose2442] Logging into account
[FretfulLyingPumpedCrane7706] Logging into account
[PuffyDapperLamentableShrew7905] Logging into account
[PuffyDapperLamentableShrew7905] Successfully logged into account
[UnbecomingManyLevelMongoose2442] Successfully logged into account
[FretfulLyingPumpedCrane7706] Successfully logged into account
[PuffyDapperLamentableShrew7905] Connected to CSGO GameCoordinator
[UnbecomingManyLevelMongoose2442] Connected to CSGO GameCoordinator
[FretfulLyingPumpedCrane7706] Connected to CSGO GameCoordinator
[PuffyDapperLamentableShrew7905] Has encountered an error
Error: Failed to send commend: Timeout
    at Timeout._onTimeout (C:\Users\Wiktor\Desktop\csgo-commend-bot-legacy\helpers\account.js:137:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[UnbecomingManyLevelMongoose2442] Has encountered an error
Error: Failed to send commend: Timeout
    at Timeout._onTimeout (C:\Users\Wiktor\Desktop\csgo-commend-bot-legacy\helpers\account.js:137:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[FretfulLyingPumpedCrane7706] Has encountered an error
Error: Failed to send commend: Timeout
    at Timeout._onTimeout (C:\Users\Wiktor\Desktop\csgo-commend-bot-legacy\helpers\account.js:137:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Successfully sent 0/3 commends, 3 commends failed
PS C:\Users\Wiktor\Desktop\csgo-commend-bot-legacy>`

**Comment by BeepFelix** [comment]
What `METHOD` are you using in the config?

**Comment by wiktor000** [comment]
i dont have this option `{
	"SteamAPIKey": "B5003673E123547788A63F********",
	"AccountToCommend": "https://steamcommunity.com/profiles/76561198951927206",
	"CommendsToSend": 3,
	"Commend": {
		"Friendly": true,
		"Teacher": true,
		"Leader": true
	},
	"AccountCooldown": 43200000,
	"RateLimitedCooldown": 5400000,
	"Chunks": {
		"CommendsPerChunk": 100,
		"SwitchProxyEvery": 2,
		"TimeBetweenChunks": 60000,
		"TimeBetweenConnectionAndSending": 2000,
		"BeautifyDelay": 10000
	},
	"Proxies": [

	]
}
`

**Comment by BeepFelix** [comment]
You're using an old version. Download the latest one and fully remake your config.

**Comment by wiktor000** [comment]
BeepFelix do you have a discord ?

**Comment by BeepFelix** [comment]
The only way to context me on Discord is via DM. You can find my Discord tag on the left side of my [Github Profile](https://github.com/BeepFelix)

**Comment by wiktor000** [comment]
Please accept
