### ISSUE TITLE
Invalid success code

### ISSUE THREAD

**Issue by nikindreus** [BeepFelix/csgo-commend-bot#70]
![Screenshot_1](https://user-images.githubusercontent.com/47863887/61584399-a0cbfd00-ab4f-11e9-8cee-0a0c4fec0f41.png)

**Comment by BeepFelix** [comment]
CSGO refused the commend. According to [SteamErrors.com](https://steamerrors.com/) it just means `Fail`. There isn't much I can say to this. Maybe commended too much with those accounts?

**Comment by nikindreus** [comment]
Yes, it has already been used 3 times today.
But why did it take this account from the database?
![Screenshot_2](https://user-images.githubusercontent.com/47863887/61584513-a0346600-ab51-11e9-908d-74de1508b6e3.png)

**Comment by BeepFelix** [comment]
It shouldn't and I never had that happen either. It could also be just something weird going on at Valve.

**Comment by nikindreus** [comment]
I understood. The problem was in the full hard disk xD
![Screenshot_3](https://user-images.githubusercontent.com/47863887/61584562-86dfe980-ab52-11e9-817f-76fa1e42e20d.png)
