### ISSUE TITLE
commends gone!

### ISSUE THREAD

**Issue by Falghere** [BeepFelix/csgo-commend-bot#74]
Has anyone also lost commends?

I was with 69K of commends there today I lost almost everything I am only with 3.5K

someone lost too?

**Comment by BeepFelix** [comment]
Does the script still work?

**Comment by dusty-dusty** [comment]
The script still works. I think its because steam removed the accounts that you commended on. I had 90 accounts disabled but my commends did not go away.

**Comment by Falghere** [comment]
> Does the script still work?
I saw that there were updates to the script ...

I downloaded the update and now started giving this error ...

what could it be?
![image](https://user-images.githubusercontent.com/16209066/62227643-ac5ec580-b392-11e9-9a99-1a08e52eaa55.png)

**Comment by BeepFelix** [comment]
Don't use `auto` in `serverID` field as per #76

**Comment by Falghere** [comment]
I thought the automatic was already working ... anyway thanks for the update

**Comment by BeepFelix** [comment]
I released it too early without proper testing.

**Comment by Falghere** [comment]
ok

**Comment by Falghere** [comment]
@BeepFelix any news about "auto"??

**Comment by BeepFelix** [comment]
No.

When its done.

**Comment by Falghere** [comment]
@BeepFelix 

I have a request here to be made ...

I have some buyers of mine who buy the compliments but don't like to receive all ...

for example :

they buy 100 compliments
 but they want

90 in leader
95 in teatcher
80 in friendly

But there is no way to do this in the correct script?
I would have to do 1 for 1 ...
Isn't there a way for you to adapt this in the future? it would be interesting

**Comment by BeepFelix** [comment]
There is, its simple math but I don't see a reason for it at the current moment. I might add it when I get bored.

For now you can just start the script multiple times one after another, one 80 on all, then 10 on leader & teacher and finally 5 on teacher.

**Comment by BeepFelix** [comment]
Boredom came early: cf187527792c0449e1f378adeff687b807cb7e1c

**Comment by Falghere** [comment]
Ooh thanks so much!! I'm very waiting for the "auto"

**Comment by KillSecurite** [comment]
Can you help me very much?  Avast#0610

**Comment by Falghere** [comment]
> Can you help me very much? Avast#0610

tell for us the error so we can help you

**Comment by KillSecurite** [comment]
I can not configure and install it

**Comment by KillSecurite** [comment]
http://prntscr.com/op5fj3

**Comment by BeepFelix** [comment]
1. My Discord tag is on my Github profile on the left side
2. You can always open your own issue thread instead of using someone elses
3. Your config.json is invalid.

**Comment by SubVinni** [comment]
@Falghere Where did you buy all these steam accounts?

**Comment by Falghere** [comment]
@SubVinni i can sell for u some ones if u wanted...

@BeepFelix 
Is there any way to remove the commends?

**Comment by SubVinni** [comment]
@Falghere price?

**Comment by Falghere** [comment]
@SubVinni 25$ = 5K

**Comment by SubVinni** [comment]
@Falghere add me discord Sub#5278

**Comment by BeepFelix** [comment]
There is currently no way to remove commends.

**Comment by BeepFelix** [comment]
As this is somewhat old and also not really related to the commend bot itself but rather Valve removing commends which was unconfirmed I am not closing this issue.
