### ISSUE TITLE
"auto" doesn't work for "serverID"

### ISSUE THREAD

**Issue by BeepFelix** [BeepFelix/csgo-commend-bot#76]
The server ID finder currently does not work. I'll work on this later and hope to figure it out in a few weeks or so.

Also mentioned in #73

**Comment by Falghere** [comment]
any news about "auto"?

**Comment by BeepFelix** [comment]
no

**Comment by apcika20** [comment]
does serverIP works?

**Comment by BeepFelix** [comment]
> does serverIP works?

Yes

**Comment by apcika20** [comment]
iam getting this error "Cannot read property 'toUpperCase' of underfiend ...

**Comment by BeepFelix** [comment]
> iam getting this error "Cannot read property 'toUpperCase' of underfiend ...

Full error log?

**Comment by apcika20** [comment]
![error](https://user-images.githubusercontent.com/43793339/63514664-21d53600-c4fa-11e9-9ad0-3a5f6b1c9dd8.png)

**Comment by BeepFelix** [comment]
You don't have a field called `serverID`. You are suppose to put the IP inside of the `serverID` field. Not create a new field.

**Comment by apcika20** [comment]
oh thanks i thought i must change serverID to serverIP

**Comment by Falghere** [comment]
any news about "auto"?

**Comment by BeepFelix** [comment]
I'll post it here when there are any.

**Comment by BeepFelix** [comment]
Check this out 14a059cf7b2654eacfbf4401948197d172999cf2

**Comment by BeepFelix** [comment]
No more issues have been reported with this feature in over 2 weeks. Assuming it works as intended.
