### ISSUE TITLE
Lot of error in console today but was working yesterday

### ISSUE THREAD

**Issue by Marcofurio30** [BeepFelix/csgo-commend-bot#78]
Error in console : 
![commend1](https://user-images.githubusercontent.com/42481322/62403392-16db5580-b58d-11e9-99dd-a08cdc93d7f0.PNG)
So i tried to npm install steam-user and now i get this : 
![commend2](https://user-images.githubusercontent.com/42481322/62403398-20fd5400-b58d-11e9-882e-0959692f2f67.PNG)
 I read LoggedElsewhere but the account are offline at the moment.
And i don't unerstand bcz it was working yesterday...

**Comment by BeepFelix** [comment]
First image: You lost connection to Steam.

Second image: Steam tells the script someone else is logged into the account, therefore it errors. There is nothing I can do about that. That's just something Steam does and I doubt Steam lies.

**Comment by Marcofurio30** [comment]
I've just tried again and now it shows again the first image

**Comment by BeepFelix** [comment]
Those are Steam errors, thats nothing I can really do.

**Comment by Marcofurio30** [comment]
Ok :/ Thanks for the fast reply
