### ISSUE TITLE
Working but...

### ISSUE THREAD

**Issue by SubVinni** [BeepFelix/csgo-commend-bot#79]
http://prntscr.com/oob220
Just one account is send the commend

**Comment by BeepFelix** [comment]
What

**Comment by SubVinni** [comment]
Sorry, i'm a newbie on this site

**Comment by BeepFelix** [comment]
The recent update changed [the config](https://github.com/BeepFelix/csgo-commend-bot#config).

It is no longer `true` or `false`, you now have to input a number for the amount of commends you want for this specific option.

**Comment by SubVinni** [comment]
Ok Thanks
