### ISSUE TITLE
not workink

### ISSUE THREAD

**Issue by sparkdz** [BeepFelix/csgo-commend-bot#80]
The "method" option only allows for "LOGIN" or "SERVER" value. Please refer to                       the README for more information.
--

![Screenshot_1](https://user-images.githubusercontent.com/18377015/62697685-88773180-b9db-11e9-83d1-02e25f76bef5.jpg)

**Comment by BeepFelix** [comment]
Read the error and look at your config

**Comment by sparkdz** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/18377015/62731150-d1ea6f80-ba21-11e9-99ee-4252ce37f117.jpg)
plz help me

**Comment by BeepFelix** [comment]
You did something wrong in your config. Paste it here *but remove API key and account details before posting*

**Comment by JekProGamer** [comment]
http://prntscr.com/oqkq1e

**Comment by JekProGamer** [comment]
http://prntscr.com/oqku30 
ошибка

**Comment by sparkdz** [comment]
ty it's working
