### ISSUE TITLE
List Not Working Accounts

### ISSUE THREAD

**Issue by SubVinni** [BeepFelix/csgo-commend-bot#81]
![Screenshot_3](https://user-images.githubusercontent.com/41969935/62838200-435b3580-bc4f-11e9-9445-afd8766a51ad.png)

[Object] should be the account name?

**Comment by BeepFelix** [comment]
Correct, fixing that right now

**Comment by BeepFelix** [comment]
Should be fixed now if you re-download.

**Comment by SubVinni** [comment]
Another question, if an account get "TimeOut" error, does she cooldown in the same way as if she had commended?

**Comment by BeepFelix** [comment]
Yes.

But you can use the account again for the same target after the cooldown is over

**Comment by SubVinni** [comment]
oh right.

http://prntscr.com/orb4f3  -- Fixed
