### ISSUE TITLE
Need help，pls

### ISSUE THREAD

**Issue by moge2019** [BeepFelix/csgo-commend-bot#82]
[yongge0033] Failed to login and has been marked as invalid (20/20) {
  eresult: 5,
  name: 'Error',
  message: 'InvalidPassword',
  stack: 'Error: InvalidPassword\n' +
    '    at SteamUser.<anonymous> (C:\\Users\\Administrator\\Desktop\\csgo-comme
nd-bot-master\\node_modules\\steam-user\\components\\logon.js:454:16)\n' +
    '    at C:\\Users\\Administrator\\Desktop\\csgo-commend-bot-master\\node_mod
ules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (C:\\Users\\Administrator\\Desktop\\csgo-commend
-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36
:12)\n' +
    '    at SteamUser._handleMessage (C:\\Users\\Administrator\\Desktop\\csgo-co
mmend-bot-master\\node_modules\\steam-user\\components\\messages.js:532:24)\n' +

    '    at SteamUser._handleNetMessage (C:\\Users\\Administrator\\Desktop\\csgo
-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:467:7)\n'
 +
    '    at SteamUser.processMulti (C:\\Users\\Administrator\\Desktop\\csgo-comm
end-bot-master\\node_modules\\steam-user\\components\\messages.js:559:9)\n' +
    '    at SteamUser.<anonymous> (C:\\Users\\Administrator\\Desktop\\csgo-comme
nd-bot-master\\node_modules\\steam-user\\components\\messages.js:553:16)\n' +
    '    at C:\\Users\\Administrator\\Desktop\\csgo-commend-bot-master\\node_mod
ules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)'
}
 Chunk 1/2 finished with 0 successful commends and 20 failed commends
 Waiting 300000ms...

**Comment by BeepFelix** [comment]
Read the first three lines.

**Comment by moge2019** [comment]
I know the first three lines, but I don't know how to correct them.
I am a rookie, please help to correct the mistakes, thank you!

>

**Comment by Falghere** [comment]
message: 'InvalidPassword',
message: 'InvalidPassword',
message: 'InvalidPassword',

**Comment by moge2019** [comment]
Tips message: 'InvalidPassword',But my password is correct, how to solve it?

**Comment by BeepFelix** [comment]
Its invalid then. Steam says its invalid not the bot.

**Comment by moge2019** [comment]
I'm a rookie. I can't solve this problem. I've collapsed.

**Comment by moge2019** [comment]
I have no way! I'm desperate! But thank you!

**Comment by BeepFelix** [comment]
Download [SQLiteBrowser](https://sqlitebrowser.org) and open up the `accounts.sqlite`. Click on `Browse Data` and select `accounts`. Then check if your passwords are actually wrong in there.

**Comment by moge2019** [comment]
If you can improve this program a little, let the novice just enter the server address and account password, and then execute, it will be the good news for the novice!

**Comment by BeepFelix** [comment]
Just follow this: https://www.youtube.com/watch?v=IRNkxAzeBVU

The instructions are not hard.

**Comment by moge2019** [comment]
Thank you. There are new problems.
 name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\Administrator\\Desktop\\csgo-commend-
bot-master\\helpers\\GameCoordinator.js:154:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}

**Comment by BeepFelix** [comment]
What method are you using? `LOGIN` or `SERVER`

**Comment by moge2019** [comment]
SERVER

**Comment by BeepFelix** [comment]
Are you actually connected to the server and have the **correct** same ServerID/Server IP in the `serverID` field of the config?

**Comment by moge2019** [comment]
i get,thank you!

**Comment by moge2019** [comment]
New problems，steam guard required

**Comment by BeepFelix** [comment]
Disable it then.

**Comment by moge2019** [comment]
How to disable it?

**Comment by BeepFelix** [comment]
Log into the account and go here https://store.steampowered.com/twofactor/manage

**Comment by moge2019** [comment]
i get,thank you bro!

**Comment by moge2019** [comment]
Suggestion: Increase the input link of login authentication number. When the new number needs login authentication, you can enter the authentication code manually instead of closing the verification.

**Comment by moge2019** [comment]
Suggestion: Increase the input link of login authentication number. When the new number needs login authentication, you can input the verification code manually instead of closing the verification, because the verification of hundreds of numbers is too time-consuming and not conducive to steam safety. 
Sorry, I use machine translation, forgive my poor English.
