### ISSUE TITLE
Accounts.txt

### ISSUE THREAD

**Issue by adingy2** [BeepFelix/csgo-commend-bot#83]
Hello! First batch was successful 11/11 accounts (which I entered user:pass manually) after first batch i tried to execute it again it it says 0/11 accounts now but it says these accounts still have 2 commends left to give. How do I use them again? Do I have to re-enter all the account details manually? I have an accounts.txt file but I think it cannot be read properly this is the format of the .txt file

user:pass
user:pass
user:pass
.....

Am I doing it wrong? Because typing the accounts manually is really tiring.

**Comment by BeepFelix** [comment]
You wait 8 hours.

You can give 3 commends every 24 hours.

24 hours / 3 commends = 8 hours per commend.

**Comment by adingy2** [comment]
Ohh I see thank you for quick response! One more thing... The .txt file with the accounts, I tried adding them by using the option: Import from username:password file after doing that it says 0/11 accounts are not working (this is before the succesful first batch)

**Comment by BeepFelix** [comment]
If the accounts already exist in the database it won't add them again.

**Comment by moge2019** [comment]
My account password is not wrong, but I have been prompted wrong, has been unsuccessful, this is too difficult to use.

**Comment by BeepFelix** [comment]
> My account password is not wrong, but I have been prompted wrong, has been unsuccessful, this is too difficult to use.

You responded to the wrong issue thread. [Go to your own.](https://github.com/BeepFelix/csgo-commend-bot/issues/82)

**Comment by adingy2** [comment]
@BeepFelix when I try adding the accounts.txt file cmd says it failed to find the accounts.txt file even if i pasted it in the csgo-commend-bot-master directory.

**Comment by BeepFelix** [comment]
Are you sure the actual file is not called `accounts.txt.txt`

**Comment by adingy2** [comment]
@BeepFelix No sir its just accounts.txt am I naming it wrong? should it be accounts.txt.txt?

**Comment by adingy2** [comment]
@BeepFelix 
![accontssss](https://user-images.githubusercontent.com/27999151/63313221-4f718200-c336-11e9-9a1a-117d8c481adf.JPG)

**Comment by BeepFelix** [comment]
You have file extensions enabled. The file is actually called `accounts.txt.txt` due to the hidden extension in there.

**Comment by adingy2** [comment]
@BeepFelix Fixed!!! Thank you I didnt know about that :)
