### ISSUE TITLE
Suggestion: Increase the input link of login authentication number.

### ISSUE THREAD

**Issue by moge2019** [BeepFelix/csgo-commend-bot#84]
Suggestion: Increase the input link of login authentication number. When the new number needs login authentication, you can input the verification code manually instead of closing the verification, because the verification of hundreds of numbers is too time-consuming and not conducive to steam safety.
Sorry, I use machine translation, forgive my poor English.

**Comment by BeepFelix** [comment]
That makes no sense.

**Comment by moge2019** [comment]
It's very meaningful to enter the validation code manually. It's very necessary. Trust my brother, thank you!

**Comment by BeepFelix** [comment]
What validation code? And why too time-consuming? 

The only code there is to enter is your Steam Guard Code when you use the script, which is once at the beginning.

**Comment by moge2019** [comment]
yes，it's the need for steam input protection.But I couldn't type it. The dialog showed the error directly.

**Comment by moge2019** [comment]
Where should I input the steam protection code?

**Comment by BeepFelix** [comment]
It only asks for Steam Guard code when its your **target** account requiring it. If a bot needs Steam Guard code it will not allow you to enter it.

You have to disable Steam Guard on all of your bot accounts manually.

**Comment by moge2019** [comment]
I have too many robots. Manual prohibition is too much trouble.

**Comment by moge2019** [comment]
[yongge0052] Requires a Steam Guard code and has been marked as invalid (11/20)
 {
  name: 'Error',
  message: 'Steam Guard required',
  stack: 'Error: Steam Guard required\n' +
    '    at SteamUser.steamGuard (C:\\Users\\Administrator\\Desktop\\csgo-commen
d-bot-master\\helpers\\account.js:80:12)\n' +
    '    at SteamUser.emit (events.js:203:13)\n' +
    '    at SteamUser._steamGuardPrompt (C:\\Users\\Administrator\\Desktop\\csgo
-commend-bot-master\\node_modules\\steam-user\\components\\logon.js:562:8)\n' +
    '    at SteamUser.<anonymous> (C:\\Users\\Administrator\\Desktop\\csgo-comme
nd-bot-master\\node_modules\\steam-user\\components\\logon.js:428:9)\n' +
    '    at C:\\Users\\Administrator\\Desktop\\csgo-commend-bot-master\\node_mod
ules\\steam-user\\components\\classes\\HandlerManager.js:37:12\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at HandlerManager.emit (C:\\Users\\Administrator\\Desktop\\csgo-commend
-bot-master\\node_modules\\steam-user\\components\\classes\\HandlerManager.js:36
:12)\n' +
    '    at SteamUser._handleMessage (C:\\Users\\Administrator\\Desktop\\csgo-co
mmend-bot-master\\node_modules\\steam-user\\components\\messages.js:532:24)\n' +

    '    at SteamUser._handleNetMessage (C:\\Users\\Administrator\\Desktop\\csgo
-commend-bot-master\\node_modules\\steam-user\\components\\messages.js:467:7)\n'
 +
    '    at SteamUser.processMulti (C:\\Users\\Administrator\\Desktop\\csgo-comm
end-bot-master\\node_modules\\steam-user\\components\\messages.js:559:9)'

I have more than 3000 accounts. I log in and turn off steam protection manually. It's a huge workload.

**Comment by BeepFelix** [comment]
Disabling Steam Guard is not within scope of this project.

**Comment by moge2019** [comment]
Disabling Steam Guard  need a one-by-one login shutdown，The workload is also huge.

**Comment by moge2019** [comment]
Is there no better solution than closing?

**Comment by BeepFelix** [comment]
Ask someone to write you a script to disable Steam Guard in bulk. This is not within scope of this project.

**Comment by moge2019** [comment]
In fact, the solution is not only to disable Steam Guard, but also to input the verification code when it prompts the verification code. Why close it?

**Comment by BeepFelix** [comment]
There is no reason to prompt for Steam guard code every time a bot needs it, thats massively wasted time.

**Comment by moge2019** [comment]
Robot login only needs the first time to input the authentication code, and then it does not need to input. That's all.

**Comment by moge2019** [comment]
Excuse me for my English communication through machine translation.

**Comment by BeepFelix** [comment]
> Robot login only needs the first time to input the authentication code, and then it does not need to input. That's all.

I know this, but some would not like this. Me for example, I wouldn't want my process to be interrupted by only a few accounts not having Steam Guard disabled. There are people who sell commends with this script, some automated it. I wouldn't want theor process to get interrupted.

**Comment by moge2019** [comment]
Can you set it up like this? If you disable Steam Guard's account, you don't enter a validation code. If you don't disable it, you enter it.

**Comment by BeepFelix** [comment]
That would already be the case. But lets say under my 40k accounts one doesn't has Steam Guard active and I do a bulk commendation without looking at it, having one account freeze everything is stupid.

**Comment by moge2019** [comment]
My accounts are all revolving hang-up time, with HourBoostr or Archi's SC Farm, 10 accounts in turn, there is no freezing problem.

**Comment by BeepFelix** [comment]
"freeze" as in waiting for your input.

I am closing this issue as I will not add the option to enter Steam Guard code for bots anyways.
