### ISSUE TITLE
Timeout errors

### ISSUE THREAD

**Issue by bramvm1** [BeepFelix/csgo-commend-bot#85]
Hey there, If I use the bot it usually runs fine for the first 50commends. After that I keep getting timeout errors. Its not the accounts because I tested it with fresh accounts. It also made them activate steam guard for some reason. tested login before use and after. I hear from some people they can run this without any issues so I think I should be able to fix this. thx

**Comment by BeepFelix** [comment]
>If I use the bot it usually runs fine for the first 50commends

What is your config?

>It also made them activate steam guard for some reason

Steam automatically does this when someone logs in for the first time.

**Comment by bramvm1** [comment]
I Use the default config. 20 20 20. with default settings and server. mode

**Comment by BeepFelix** [comment]
So if you use 20, that means you manually restart the script after 20 commends and it fails after 50 anyways?

**Comment by bramvm1** [comment]
Yes I manually restart every 20. and the errors come. kinda random sometimes 50 soemtimes 100. But when they come. They stay for a while. If I keep doing node index. js

**Comment by BeepFelix** [comment]
Did you try simply doing 100 100 100 and letting that run?

**Comment by bramvm1** [comment]
No. Some1 told me I wasnt allowed to. So I am able to?

**Comment by BeepFelix** [comment]
Why would you not be allowed to? The script automatically chunks everything into parts and has a delay between each chunk to prevent limits.

If you wouldn't be allowed to I wouldn't have put it in the config.

**Comment by bramvm1** [comment]
That might be the issue here. I keep spamming index.js every 20

**Comment by BeepFelix** [comment]
Maybe, maybe not. There is suppose to be a ~5 minute delay between every 20 commends. Try it out.

**Comment by bramvm1** [comment]
I think this fixed my issue. Waiting 5mins every 20commends. Thx alot.
