### ISSUE TITLE
Timeout error , I'm still getting that error tho.

### ISSUE THREAD

**Issue by bramvm1** [BeepFelix/csgo-commend-bot#86]
[6nLzVGBBuZ] Failed to commend (20/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +
    '    at Timeout._onTimeout (C:\\Users\\MrPepper\\Desktop\\csgo-commend-bot-master\\helpers\\GameCoordinator.js:154:12)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}

**Comment by BeepFelix** [comment]
The error sometimes happens, I don't know why. It seems to be somewhat random but doing 20 every 5 minutes seems to give the best results. I noticed some bots work just fine while others don't work.

**Comment by BeepFelix** [comment]
Closed due to inactivity
