### ISSUE TITLE
Error: LoggedInElsewhere

### ISSUE THREAD

**Issue by Vejas04** [BeepFelix/csgo-commend-bot#87]
Hello everybody,

After i start the bot with the "LOGIN" method sometimes this message comes up:

Error: LoggedInElsewhere

 The problem is that i logged me out everywhere and it still doesnt goes :/

Thank you for helping!

**Comment by BeepFelix** [comment]
Are you sure its on the target account and not on one of the bots?

**Comment by Vejas04** [comment]
The target account is not in the accounts list...

**Comment by BeepFelix** [comment]
I am talking about the error, does it happen at the very beginning when your target account logs in or does it happen while the commending is happening?

If it happens while the commending is happening it could also be related to one of the bot accounts.

**Comment by Vejas04** [comment]
Mostly the error comes up while it is sending the commends. For example at the 4 one.

**Comment by BeepFelix** [comment]
Does it say one of the bots errored? What is the exact log?

**Comment by Vejas04** [comment]
Well it is currently working idk why. But yesterday it didnt. Sorry.

**Comment by Vejas04** [comment]
But i have one more question. Is it possible to edit the whole commend bot like this that all commends will come instantly?

**Comment by BeepFelix** [comment]
I heard about these issues with `LoggedInElsewhere` before but was never able to pin it down to anything.

---

You can try messing with `perChunk` and `betweenChunks`, nobody is stopping you. From my tests the current ones worked fairly good.

**Comment by Vejas04** [comment]
Okay thanks a lot. One more thing.
Is there a away to removr the not working accounts from the account list automaticly? Because i have a lot of accounts but lot of those doesnt even work. And i dont want to remove them manually.

Thanks for the quick replies

**Comment by BeepFelix** [comment]
You can't remove all non-working accounts at once but you don't have to either. The script will automatically ignore every account marked as unusable.

**Comment by Vejas04** [comment]
Ah okay. Thank you very much. (Maybe a tool like this still would be cool)

**Comment by BeepFelix** [comment]
Yeah, I'll leave this issue open and close it once I added that.

**Comment by Vejas04** [comment]
Thanks a lot :)

**Comment by BeepFelix** [comment]
That makes no sense

**Comment by Vejas04** [comment]
Oh okay.

**Comment by Vejas04** [comment]
oh okay

**Comment by Vejas04** [comment]
Is there a way how to get steam accounts in bulk?
Do you know any ways? Because i tried to download a steam account generator but it doesnt work well after i set the API Key for 2Captcha.

**Comment by BeepFelix** [comment]
I do not.

**Comment by Jaeger33211** [comment]
if you want to remove the not working accounts do:
Delete from accounts where operational = '0'

**Comment by BeepFelix** [comment]
Closing in favor of #90
