### ISSUE TITLE
Timeout (Accounts not used count)

### ISSUE THREAD

**Issue by Alexandr987** [BeepFelix/csgo-commend-bot#88]
Is it possible to make idk maybe file with accounts which was not used (got error) because i always got about 1-4 accounts from 20 with this error

**Comment by BeepFelix** [comment]
I have no idea what this means

**Comment by Alexandr987** [comment]
i got errors like this - https://i.imgur.com/6OwxQgi.png  ~1-4/20 accounts per tick (5min) 
Is it possible to make txt file with accounts which not used in bot

**Comment by BeepFelix** [comment]
There is no way to get a list of accounts which failed to commend the target.

**Comment by Alexandr987** [comment]
ok, ty
