### ISSUE TITLE
Error:Could not find online server

### ISSUE THREAD

**Issue by X1FX** [BeepFelix/csgo-commend-bot#92]
Hi, I have a problem ... No matter what server I go to, this error is constantly. How to fix it? There is no antivirus, maybe this is due to ports?
http://prntscr.com/p32v61

I did not edit anything in the config except url, api and id server

**Comment by BeepFelix** [comment]
Read what the README says. 

> Make sure to only include the stuff between the brackets **and the brackets themselves.**

and look at the example

> On a Valve server it will look like this: Connected to =[A:1:3849827331:12657]:0 > [A:1:3849827331:12657].

**Comment by X1FX** [comment]
Damn, thanks! I'm a fool :)   
But now another mistake ...
http://prntscr.com/p32z1z

**Comment by BeepFelix** [comment]
I keep getting more reports of this error but I do not know how to replicate it.

I will try some stuff out and see if it works.

Closing this issue because #90 is the same error, keep discussion about that error there.
