### ISSUE TITLE
0 accounts out of 331 are available (after commending one account)

### ISSUE THREAD

**Issue by kblade07** [BeepFelix/csgo-commend-bot#93]
Hey, im back with one question.
The commend bot works better than before, so thank you very much for keeping it updated.
After i commended one account, ive got this error. 
`0 accounts out of 331 are available `
In the past i used to delete the database and then it worked. But you told me in another Topic that its pretty bad to delete/reset it so i wont do it again.
Does this have anything to do with the "cooldown" section in the config.json?
Thats still default, i didnt changed anything and its 480 minutes, 8 hours.
I guess that is the amout of cooldown for the accounts before I can use them again.
But i see in the changelog that something is new:

`Add the ability to commend three times with one account per 24 hours instead of once every 8 hours`

So I used the accounts for 1 out of 3 commends. What should i change to be able to use them 3/3 commends in 24h? Thanks for your help and time!

**Comment by BeepFelix** [comment]
Just wait 8 hours. There is no way to use all 3 faster. Just commend once every 8 hours.

**Comment by kblade07** [comment]
Oh, I  understand now. Thanks
