### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by aryoow** [BeepFelix/csgo-commend-bot#95]
[7llGupnVvlH9] Failed to commend (10/20) {
  name: 'Error',
  message: 'Failed to send message: Timeout',
  stack: 'Error: Failed to send message: Timeout\n' +

**Comment by BeepFelix** [comment]
If you followed the README correctly then I can just say: Happens sometimes. Nothing really I can do as far as I know.

**Comment by aryoow** [comment]
so what should i do to fix this? i always getting this error every time from the beginning i download this

**Comment by BeepFelix** [comment]
What is your config

**Comment by aryoow** [comment]
"method": "SERVER",
	"target": "https://steamcommunity.com/id/76561198291869321",
	"serverID": "74.91.112.208:27015",
	"matchID": "0",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,

**Comment by aryoow** [comment]
i try at git bash, cmd, powershell, c9, Codeanywhere but the result is same, Timeout

**Comment by BeepFelix** [comment]
I do not know. I **assume** its because the server might be full.

**Comment by aryoow** [comment]
the server not full, because i choose empty server

**Comment by BeepFelix** [comment]
Then I can't help, I don't know why it happens.

**Comment by aryoow** [comment]
ok then, i hope you can find the solution
