### ISSUE TITLE
Inconsistent Commendation Numbers

### ISSUE THREAD

**Issue by markbmullins** [BeepFelix/csgo-commend-bot#96]
- Account had commendations like so: 12, 14, 15

- Had 37 accounts in database, about half new, half had commended 24 hours previously

- Ran script with all commends set to 37

- Script ran in two chunks, all commends were successes

- Expected outcome: commends are now 45, 51, 52

- Actual outcome: commends are now 38, 38, 38

**Comment by BeepFelix** [comment]
Are you sure none of the accounts had previously commended the target?

**Comment by markbmullins** [comment]
Approx. half had commended 24 hours previously.

**Comment by BeepFelix** [comment]
But did they commend the same person before or not?

**Comment by markbmullins** [comment]
Oh, yes I believe so.

**Comment by markbmullins** [comment]
I see what you're saying, I hit max number of commends.

**Comment by BeepFelix** [comment]
A bot can only commend **the same** target once, but you can commend as many **different** targets as you want.
